// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module bnn_xcel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_state18 = 24'd131072;
parameter    ap_ST_fsm_state19 = 24'd262144;
parameter    ap_ST_fsm_state20 = 24'd524288;
parameter    ap_ST_fsm_state21 = 24'd1048576;
parameter    ap_ST_fsm_state22 = 24'd2097152;
parameter    ap_ST_fsm_state23 = 24'd4194304;
parameter    ap_ST_fsm_state24 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] input_r_address0;
output   input_r_ce0;
input  [0:0] input_r_q0;
output  [3:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] ap_return;

(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [511:0] grp_flatten_fu_247_ap_return;
reg   [511:0] reshaped_reg_374;
wire    ap_CS_fsm_state16;
wire    grp_flatten_fu_247_ap_ready;
wire    grp_flatten_fu_247_ap_done;
wire   [8:0] m_fu_296_p2;
reg   [8:0] m_reg_382;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln246_fu_290_p2;
reg   [255:0] tmp_fu_317_p4;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state21;
wire  signed [15:0] max_V_fu_327_p1;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln260_fu_331_p2;
wire   [3:0] select_ln261_fu_352_p3;
wire    ap_CS_fsm_state24;
wire   [15:0] select_ln261_1_fu_360_p3;
wire   [3:0] i_fu_368_p2;
reg   [8:0] input_padded_address0;
reg    input_padded_ce0;
reg    input_padded_we0;
reg   [0:0] input_padded_d0;
wire   [0:0] input_padded_q0;
reg   [7:0] conv1_address0;
reg    conv1_ce0;
reg    conv1_we0;
wire   [15:0] conv1_q0;
reg    conv1_ce1;
wire   [15:0] conv1_q1;
reg   [5:0] conv1_pooled_address0;
reg    conv1_pooled_ce0;
reg    conv1_pooled_we0;
wire   [15:0] conv1_pooled_q0;
reg   [6:0] conv1_pooled_padded_address0;
reg    conv1_pooled_padded_ce0;
reg    conv1_pooled_padded_we0;
reg   [15:0] conv1_pooled_padded_d0;
wire   [15:0] conv1_pooled_padded_q0;
reg   [5:0] conv2_address0;
reg    conv2_ce0;
reg    conv2_we0;
wire   [31:0] conv2_q0;
reg    conv2_ce1;
wire   [31:0] conv2_q1;
reg   [3:0] conv2_pooled_address0;
reg    conv2_pooled_ce0;
reg    conv2_pooled_we0;
wire   [31:0] conv2_pooled_q0;
reg   [7:0] dense1_V_address0;
reg    dense1_V_ce0;
reg    dense1_V_we0;
wire   [10:0] dense1_V_q0;
reg   [3:0] dense2_V_address0;
reg    dense2_V_ce0;
reg    dense2_V_we0;
wire   [9:0] dense2_V_q0;
wire    grp_conv_16_32_10_4_s_fu_198_ap_start;
wire    grp_conv_16_32_10_4_s_fu_198_ap_done;
wire    grp_conv_16_32_10_4_s_fu_198_ap_idle;
wire    grp_conv_16_32_10_4_s_fu_198_ap_ready;
wire   [6:0] grp_conv_16_32_10_4_s_fu_198_input_r_address0;
wire    grp_conv_16_32_10_4_s_fu_198_input_r_ce0;
wire   [5:0] grp_conv_16_32_10_4_s_fu_198_output_r_address0;
wire    grp_conv_16_32_10_4_s_fu_198_output_r_ce0;
wire    grp_conv_16_32_10_4_s_fu_198_output_r_we0;
wire   [31:0] grp_conv_16_32_10_4_s_fu_198_output_r_d0;
wire    grp_dense_512_256_s_fu_224_ap_start;
wire    grp_dense_512_256_s_fu_224_ap_done;
wire    grp_dense_512_256_s_fu_224_ap_idle;
wire    grp_dense_512_256_s_fu_224_ap_ready;
wire   [7:0] grp_dense_512_256_s_fu_224_output_V_address0;
wire    grp_dense_512_256_s_fu_224_output_V_ce0;
wire    grp_dense_512_256_s_fu_224_output_V_we0;
wire   [10:0] grp_dense_512_256_s_fu_224_output_V_d0;
wire    grp_dense_256_10_s_fu_232_ap_start;
wire    grp_dense_256_10_s_fu_232_ap_done;
wire    grp_dense_256_10_s_fu_232_ap_idle;
wire    grp_dense_256_10_s_fu_232_ap_ready;
wire   [3:0] grp_dense_256_10_s_fu_232_output_V_address0;
wire    grp_dense_256_10_s_fu_232_output_V_ce0;
wire    grp_dense_256_10_s_fu_232_output_V_we0;
wire   [9:0] grp_dense_256_10_s_fu_232_output_V_d0;
wire    grp_conv_1_16_18_1_s_fu_241_ap_start;
wire    grp_conv_1_16_18_1_s_fu_241_ap_done;
wire    grp_conv_1_16_18_1_s_fu_241_ap_idle;
wire    grp_conv_1_16_18_1_s_fu_241_ap_ready;
wire   [8:0] grp_conv_1_16_18_1_s_fu_241_input_r_address0;
wire    grp_conv_1_16_18_1_s_fu_241_input_r_ce0;
wire   [7:0] grp_conv_1_16_18_1_s_fu_241_output_r_address0;
wire    grp_conv_1_16_18_1_s_fu_241_output_r_ce0;
wire    grp_conv_1_16_18_1_s_fu_241_output_r_we0;
wire   [15:0] grp_conv_1_16_18_1_s_fu_241_output_r_d0;
wire    grp_flatten_fu_247_ap_start;
wire    grp_flatten_fu_247_ap_idle;
wire   [3:0] grp_flatten_fu_247_input_r_address0;
wire    grp_flatten_fu_247_input_r_ce0;
wire    grp_max_pool_32_8_s_fu_253_ap_start;
wire    grp_max_pool_32_8_s_fu_253_ap_done;
wire    grp_max_pool_32_8_s_fu_253_ap_idle;
wire    grp_max_pool_32_8_s_fu_253_ap_ready;
wire   [5:0] grp_max_pool_32_8_s_fu_253_input_r_address0;
wire    grp_max_pool_32_8_s_fu_253_input_r_ce0;
wire   [5:0] grp_max_pool_32_8_s_fu_253_input_r_address1;
wire    grp_max_pool_32_8_s_fu_253_input_r_ce1;
wire   [3:0] grp_max_pool_32_8_s_fu_253_output_r_address0;
wire    grp_max_pool_32_8_s_fu_253_output_r_ce0;
wire    grp_max_pool_32_8_s_fu_253_output_r_we0;
wire   [31:0] grp_max_pool_32_8_s_fu_253_output_r_d0;
wire    grp_max_pool_16_16_s_fu_259_ap_start;
wire    grp_max_pool_16_16_s_fu_259_ap_done;
wire    grp_max_pool_16_16_s_fu_259_ap_idle;
wire    grp_max_pool_16_16_s_fu_259_ap_ready;
wire   [7:0] grp_max_pool_16_16_s_fu_259_input_r_address0;
wire    grp_max_pool_16_16_s_fu_259_input_r_ce0;
wire   [7:0] grp_max_pool_16_16_s_fu_259_input_r_address1;
wire    grp_max_pool_16_16_s_fu_259_input_r_ce1;
wire   [5:0] grp_max_pool_16_16_s_fu_259_output_r_address0;
wire    grp_max_pool_16_16_s_fu_259_output_r_ce0;
wire    grp_max_pool_16_16_s_fu_259_output_r_we0;
wire   [15:0] grp_max_pool_16_16_s_fu_259_output_r_d0;
wire    grp_pad_1_16_9_fu_265_ap_start;
wire    grp_pad_1_16_9_fu_265_ap_done;
wire    grp_pad_1_16_9_fu_265_ap_idle;
wire    grp_pad_1_16_9_fu_265_ap_ready;
wire   [7:0] grp_pad_1_16_9_fu_265_input_r_address0;
wire    grp_pad_1_16_9_fu_265_input_r_ce0;
wire   [8:0] grp_pad_1_16_9_fu_265_output_r_address0;
wire    grp_pad_1_16_9_fu_265_output_r_ce0;
wire    grp_pad_1_16_9_fu_265_output_r_we0;
wire   [0:0] grp_pad_1_16_9_fu_265_output_r_d0;
wire    grp_pad_16_8_s_fu_272_ap_start;
wire    grp_pad_16_8_s_fu_272_ap_done;
wire    grp_pad_16_8_s_fu_272_ap_idle;
wire    grp_pad_16_8_s_fu_272_ap_ready;
wire   [5:0] grp_pad_16_8_s_fu_272_input_r_address0;
wire    grp_pad_16_8_s_fu_272_input_r_ce0;
wire   [6:0] grp_pad_16_8_s_fu_272_output_r_address0;
wire    grp_pad_16_8_s_fu_272_output_r_ce0;
wire    grp_pad_16_8_s_fu_272_output_r_we0;
wire   [15:0] grp_pad_16_8_s_fu_272_output_r_d0;
wire    grp_initialize_padded_me_1_fu_278_ap_start;
wire    grp_initialize_padded_me_1_fu_278_ap_done;
wire    grp_initialize_padded_me_1_fu_278_ap_idle;
wire    grp_initialize_padded_me_1_fu_278_ap_ready;
wire   [8:0] grp_initialize_padded_me_1_fu_278_input_r_address0;
wire    grp_initialize_padded_me_1_fu_278_input_r_ce0;
wire    grp_initialize_padded_me_1_fu_278_input_r_we0;
wire   [0:0] grp_initialize_padded_me_1_fu_278_input_r_d0;
wire    grp_initialize_padded_me_fu_284_ap_start;
wire    grp_initialize_padded_me_fu_284_ap_done;
wire    grp_initialize_padded_me_fu_284_ap_idle;
wire    grp_initialize_padded_me_fu_284_ap_ready;
wire   [6:0] grp_initialize_padded_me_fu_284_input_r_address0;
wire    grp_initialize_padded_me_fu_284_input_r_ce0;
wire    grp_initialize_padded_me_fu_284_input_r_we0;
wire   [15:0] grp_initialize_padded_me_fu_284_input_r_d0;
reg   [255:0] signed1_reg_140;
reg   [8:0] m_0_i_reg_152;
wire    ap_CS_fsm_state17;
reg   [3:0] agg_result_V_0_i_reg_164;
reg   [15:0] p_012_0_i_reg_176;
reg   [3:0] max_id_V_reg_186;
reg    grp_conv_16_32_10_4_s_fu_198_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_dense_512_256_s_fu_224_ap_start_reg;
reg    grp_dense_256_10_s_fu_232_ap_start_reg;
wire    ap_CS_fsm_state20;
reg    grp_conv_1_16_18_1_s_fu_241_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_flatten_fu_247_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_max_pool_32_8_s_fu_253_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_max_pool_16_16_s_fu_259_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_pad_1_16_9_fu_265_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_pad_16_8_s_fu_272_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_initialize_padded_me_1_fu_278_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_initialize_padded_me_fu_284_ap_start_reg;
wire   [63:0] zext_ln247_fu_302_p1;
wire   [63:0] zext_ln261_fu_337_p1;
wire   [9:0] zext_ln247_1_fu_313_p1;
wire   [0:0] icmp_ln895_fu_307_p2;
wire  signed [15:0] max_V_1_fu_342_p1;
wire   [0:0] icmp_ln895_20_fu_346_p2;
reg   [3:0] ap_return_preg;
reg   [23:0] ap_NS_fsm;
reg    ap_block_state2_on_subcall_done;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 grp_conv_16_32_10_4_s_fu_198_ap_start_reg = 1'b0;
#0 grp_dense_512_256_s_fu_224_ap_start_reg = 1'b0;
#0 grp_dense_256_10_s_fu_232_ap_start_reg = 1'b0;
#0 grp_conv_1_16_18_1_s_fu_241_ap_start_reg = 1'b0;
#0 grp_flatten_fu_247_ap_start_reg = 1'b0;
#0 grp_max_pool_32_8_s_fu_253_ap_start_reg = 1'b0;
#0 grp_max_pool_16_16_s_fu_259_ap_start_reg = 1'b0;
#0 grp_pad_1_16_9_fu_265_ap_start_reg = 1'b0;
#0 grp_pad_16_8_s_fu_272_ap_start_reg = 1'b0;
#0 grp_initialize_padded_me_1_fu_278_ap_start_reg = 1'b0;
#0 grp_initialize_padded_me_fu_284_ap_start_reg = 1'b0;
#0 ap_return_preg = 4'd0;
end

bnn_xcel_input_patde #(
    .DataWidth( 1 ),
    .AddressRange( 324 ),
    .AddressWidth( 9 ))
input_padded_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(input_padded_address0),
    .ce0(input_padded_ce0),
    .we0(input_padded_we0),
    .d0(input_padded_d0),
    .q0(input_padded_q0)
);

bnn_xcel_conv1 #(
    .DataWidth( 16 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
conv1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_address0),
    .ce0(conv1_ce0),
    .we0(conv1_we0),
    .d0(grp_conv_1_16_18_1_s_fu_241_output_r_d0),
    .q0(conv1_q0),
    .address1(grp_max_pool_16_16_s_fu_259_input_r_address1),
    .ce1(conv1_ce1),
    .q1(conv1_q1)
);

bnn_xcel_conv1_poudo #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
conv1_pooled_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_pooled_address0),
    .ce0(conv1_pooled_ce0),
    .we0(conv1_pooled_we0),
    .d0(grp_max_pool_16_16_s_fu_259_output_r_d0),
    .q0(conv1_pooled_q0)
);

bnn_xcel_conv1_povdy #(
    .DataWidth( 16 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
conv1_pooled_padded_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_pooled_padded_address0),
    .ce0(conv1_pooled_padded_ce0),
    .we0(conv1_pooled_padded_we0),
    .d0(conv1_pooled_padded_d0),
    .q0(conv1_pooled_padded_q0)
);

bnn_xcel_conv2 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
conv2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_address0),
    .ce0(conv2_ce0),
    .we0(conv2_we0),
    .d0(grp_conv_16_32_10_4_s_fu_198_output_r_d0),
    .q0(conv2_q0),
    .address1(grp_max_pool_32_8_s_fu_253_input_r_address1),
    .ce1(conv2_ce1),
    .q1(conv2_q1)
);

bnn_xcel_conv2_powdI #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
conv2_pooled_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_pooled_address0),
    .ce0(conv2_pooled_ce0),
    .we0(conv2_pooled_we0),
    .d0(grp_max_pool_32_8_s_fu_253_output_r_d0),
    .q0(conv2_pooled_q0)
);

bnn_xcel_dense1_V #(
    .DataWidth( 11 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
dense1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense1_V_address0),
    .ce0(dense1_V_ce0),
    .we0(dense1_V_we0),
    .d0(grp_dense_512_256_s_fu_224_output_V_d0),
    .q0(dense1_V_q0)
);

bnn_xcel_dense2_V #(
    .DataWidth( 10 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
dense2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dense2_V_address0),
    .ce0(dense2_V_ce0),
    .we0(dense2_V_we0),
    .d0(grp_dense_256_10_s_fu_232_output_V_d0),
    .q0(dense2_V_q0)
);

conv_16_32_10_4_s grp_conv_16_32_10_4_s_fu_198(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv_16_32_10_4_s_fu_198_ap_start),
    .ap_done(grp_conv_16_32_10_4_s_fu_198_ap_done),
    .ap_idle(grp_conv_16_32_10_4_s_fu_198_ap_idle),
    .ap_ready(grp_conv_16_32_10_4_s_fu_198_ap_ready),
    .input_r_address0(grp_conv_16_32_10_4_s_fu_198_input_r_address0),
    .input_r_ce0(grp_conv_16_32_10_4_s_fu_198_input_r_ce0),
    .input_r_q0(conv1_pooled_padded_q0),
    .output_r_address0(grp_conv_16_32_10_4_s_fu_198_output_r_address0),
    .output_r_ce0(grp_conv_16_32_10_4_s_fu_198_output_r_ce0),
    .output_r_we0(grp_conv_16_32_10_4_s_fu_198_output_r_we0),
    .output_r_d0(grp_conv_16_32_10_4_s_fu_198_output_r_d0),
    .output_r_q0(conv2_q0)
);

dense_512_256_s grp_dense_512_256_s_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_512_256_s_fu_224_ap_start),
    .ap_done(grp_dense_512_256_s_fu_224_ap_done),
    .ap_idle(grp_dense_512_256_s_fu_224_ap_idle),
    .ap_ready(grp_dense_512_256_s_fu_224_ap_ready),
    .input_read(reshaped_reg_374),
    .output_V_address0(grp_dense_512_256_s_fu_224_output_V_address0),
    .output_V_ce0(grp_dense_512_256_s_fu_224_output_V_ce0),
    .output_V_we0(grp_dense_512_256_s_fu_224_output_V_we0),
    .output_V_d0(grp_dense_512_256_s_fu_224_output_V_d0)
);

dense_256_10_s grp_dense_256_10_s_fu_232(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_256_10_s_fu_232_ap_start),
    .ap_done(grp_dense_256_10_s_fu_232_ap_done),
    .ap_idle(grp_dense_256_10_s_fu_232_ap_idle),
    .ap_ready(grp_dense_256_10_s_fu_232_ap_ready),
    .input_read(signed1_reg_140),
    .output_V_address0(grp_dense_256_10_s_fu_232_output_V_address0),
    .output_V_ce0(grp_dense_256_10_s_fu_232_output_V_ce0),
    .output_V_we0(grp_dense_256_10_s_fu_232_output_V_we0),
    .output_V_d0(grp_dense_256_10_s_fu_232_output_V_d0)
);

conv_1_16_18_1_s grp_conv_1_16_18_1_s_fu_241(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv_1_16_18_1_s_fu_241_ap_start),
    .ap_done(grp_conv_1_16_18_1_s_fu_241_ap_done),
    .ap_idle(grp_conv_1_16_18_1_s_fu_241_ap_idle),
    .ap_ready(grp_conv_1_16_18_1_s_fu_241_ap_ready),
    .input_r_address0(grp_conv_1_16_18_1_s_fu_241_input_r_address0),
    .input_r_ce0(grp_conv_1_16_18_1_s_fu_241_input_r_ce0),
    .input_r_q0(input_padded_q0),
    .output_r_address0(grp_conv_1_16_18_1_s_fu_241_output_r_address0),
    .output_r_ce0(grp_conv_1_16_18_1_s_fu_241_output_r_ce0),
    .output_r_we0(grp_conv_1_16_18_1_s_fu_241_output_r_we0),
    .output_r_d0(grp_conv_1_16_18_1_s_fu_241_output_r_d0)
);

flatten grp_flatten_fu_247(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_flatten_fu_247_ap_start),
    .ap_done(grp_flatten_fu_247_ap_done),
    .ap_idle(grp_flatten_fu_247_ap_idle),
    .ap_ready(grp_flatten_fu_247_ap_ready),
    .input_r_address0(grp_flatten_fu_247_input_r_address0),
    .input_r_ce0(grp_flatten_fu_247_input_r_ce0),
    .input_r_q0(conv2_pooled_q0),
    .ap_return(grp_flatten_fu_247_ap_return)
);

max_pool_32_8_s grp_max_pool_32_8_s_fu_253(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_max_pool_32_8_s_fu_253_ap_start),
    .ap_done(grp_max_pool_32_8_s_fu_253_ap_done),
    .ap_idle(grp_max_pool_32_8_s_fu_253_ap_idle),
    .ap_ready(grp_max_pool_32_8_s_fu_253_ap_ready),
    .input_r_address0(grp_max_pool_32_8_s_fu_253_input_r_address0),
    .input_r_ce0(grp_max_pool_32_8_s_fu_253_input_r_ce0),
    .input_r_q0(conv2_q0),
    .input_r_address1(grp_max_pool_32_8_s_fu_253_input_r_address1),
    .input_r_ce1(grp_max_pool_32_8_s_fu_253_input_r_ce1),
    .input_r_q1(conv2_q1),
    .output_r_address0(grp_max_pool_32_8_s_fu_253_output_r_address0),
    .output_r_ce0(grp_max_pool_32_8_s_fu_253_output_r_ce0),
    .output_r_we0(grp_max_pool_32_8_s_fu_253_output_r_we0),
    .output_r_d0(grp_max_pool_32_8_s_fu_253_output_r_d0)
);

max_pool_16_16_s grp_max_pool_16_16_s_fu_259(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_max_pool_16_16_s_fu_259_ap_start),
    .ap_done(grp_max_pool_16_16_s_fu_259_ap_done),
    .ap_idle(grp_max_pool_16_16_s_fu_259_ap_idle),
    .ap_ready(grp_max_pool_16_16_s_fu_259_ap_ready),
    .input_r_address0(grp_max_pool_16_16_s_fu_259_input_r_address0),
    .input_r_ce0(grp_max_pool_16_16_s_fu_259_input_r_ce0),
    .input_r_q0(conv1_q0),
    .input_r_address1(grp_max_pool_16_16_s_fu_259_input_r_address1),
    .input_r_ce1(grp_max_pool_16_16_s_fu_259_input_r_ce1),
    .input_r_q1(conv1_q1),
    .output_r_address0(grp_max_pool_16_16_s_fu_259_output_r_address0),
    .output_r_ce0(grp_max_pool_16_16_s_fu_259_output_r_ce0),
    .output_r_we0(grp_max_pool_16_16_s_fu_259_output_r_we0),
    .output_r_d0(grp_max_pool_16_16_s_fu_259_output_r_d0)
);

pad_1_16_9 grp_pad_1_16_9_fu_265(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_1_16_9_fu_265_ap_start),
    .ap_done(grp_pad_1_16_9_fu_265_ap_done),
    .ap_idle(grp_pad_1_16_9_fu_265_ap_idle),
    .ap_ready(grp_pad_1_16_9_fu_265_ap_ready),
    .input_r_address0(grp_pad_1_16_9_fu_265_input_r_address0),
    .input_r_ce0(grp_pad_1_16_9_fu_265_input_r_ce0),
    .input_r_q0(input_r_q0),
    .output_r_address0(grp_pad_1_16_9_fu_265_output_r_address0),
    .output_r_ce0(grp_pad_1_16_9_fu_265_output_r_ce0),
    .output_r_we0(grp_pad_1_16_9_fu_265_output_r_we0),
    .output_r_d0(grp_pad_1_16_9_fu_265_output_r_d0)
);

pad_16_8_s grp_pad_16_8_s_fu_272(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pad_16_8_s_fu_272_ap_start),
    .ap_done(grp_pad_16_8_s_fu_272_ap_done),
    .ap_idle(grp_pad_16_8_s_fu_272_ap_idle),
    .ap_ready(grp_pad_16_8_s_fu_272_ap_ready),
    .input_r_address0(grp_pad_16_8_s_fu_272_input_r_address0),
    .input_r_ce0(grp_pad_16_8_s_fu_272_input_r_ce0),
    .input_r_q0(conv1_pooled_q0),
    .output_r_address0(grp_pad_16_8_s_fu_272_output_r_address0),
    .output_r_ce0(grp_pad_16_8_s_fu_272_output_r_ce0),
    .output_r_we0(grp_pad_16_8_s_fu_272_output_r_we0),
    .output_r_d0(grp_pad_16_8_s_fu_272_output_r_d0)
);

initialize_padded_me_1 grp_initialize_padded_me_1_fu_278(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_initialize_padded_me_1_fu_278_ap_start),
    .ap_done(grp_initialize_padded_me_1_fu_278_ap_done),
    .ap_idle(grp_initialize_padded_me_1_fu_278_ap_idle),
    .ap_ready(grp_initialize_padded_me_1_fu_278_ap_ready),
    .input_r_address0(grp_initialize_padded_me_1_fu_278_input_r_address0),
    .input_r_ce0(grp_initialize_padded_me_1_fu_278_input_r_ce0),
    .input_r_we0(grp_initialize_padded_me_1_fu_278_input_r_we0),
    .input_r_d0(grp_initialize_padded_me_1_fu_278_input_r_d0)
);

initialize_padded_me grp_initialize_padded_me_fu_284(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_initialize_padded_me_fu_284_ap_start),
    .ap_done(grp_initialize_padded_me_fu_284_ap_done),
    .ap_idle(grp_initialize_padded_me_fu_284_ap_idle),
    .ap_ready(grp_initialize_padded_me_fu_284_ap_ready),
    .input_r_address0(grp_initialize_padded_me_fu_284_input_r_address0),
    .input_r_ce0(grp_initialize_padded_me_fu_284_input_r_ce0),
    .input_r_we0(grp_initialize_padded_me_fu_284_input_r_we0),
    .input_r_d0(grp_initialize_padded_me_fu_284_input_r_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 4'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln260_fu_331_p2 == 1'd1))) begin
            ap_return_preg <= agg_result_V_0_i_reg_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv_16_32_10_4_s_fu_198_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_conv_16_32_10_4_s_fu_198_ap_start_reg <= 1'b1;
        end else if ((grp_conv_16_32_10_4_s_fu_198_ap_ready == 1'b1)) begin
            grp_conv_16_32_10_4_s_fu_198_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv_1_16_18_1_s_fu_241_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_conv_1_16_18_1_s_fu_241_ap_start_reg <= 1'b1;
        end else if ((grp_conv_1_16_18_1_s_fu_241_ap_ready == 1'b1)) begin
            grp_conv_1_16_18_1_s_fu_241_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_256_10_s_fu_232_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln246_fu_290_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
            grp_dense_256_10_s_fu_232_ap_start_reg <= 1'b1;
        end else if ((grp_dense_256_10_s_fu_232_ap_ready == 1'b1)) begin
            grp_dense_256_10_s_fu_232_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_512_256_s_fu_224_ap_start_reg <= 1'b0;
    end else begin
        if (((grp_flatten_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
            grp_dense_512_256_s_fu_224_ap_start_reg <= 1'b1;
        end else if ((grp_dense_512_256_s_fu_224_ap_ready == 1'b1)) begin
            grp_dense_512_256_s_fu_224_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_flatten_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_flatten_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_flatten_fu_247_ap_ready == 1'b1)) begin
            grp_flatten_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_initialize_padded_me_1_fu_278_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_initialize_padded_me_1_fu_278_ap_start_reg <= 1'b1;
        end else if ((grp_initialize_padded_me_1_fu_278_ap_ready == 1'b1)) begin
            grp_initialize_padded_me_1_fu_278_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_initialize_padded_me_fu_284_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_initialize_padded_me_fu_284_ap_start_reg <= 1'b1;
        end else if ((grp_initialize_padded_me_fu_284_ap_ready == 1'b1)) begin
            grp_initialize_padded_me_fu_284_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_max_pool_16_16_s_fu_259_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_max_pool_16_16_s_fu_259_ap_start_reg <= 1'b1;
        end else if ((grp_max_pool_16_16_s_fu_259_ap_ready == 1'b1)) begin
            grp_max_pool_16_16_s_fu_259_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_max_pool_32_8_s_fu_253_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_max_pool_32_8_s_fu_253_ap_start_reg <= 1'b1;
        end else if ((grp_max_pool_32_8_s_fu_253_ap_ready == 1'b1)) begin
            grp_max_pool_32_8_s_fu_253_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_16_8_s_fu_272_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_pad_16_8_s_fu_272_ap_start_reg <= 1'b1;
        end else if ((grp_pad_16_8_s_fu_272_ap_ready == 1'b1)) begin
            grp_pad_16_8_s_fu_272_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pad_1_16_9_fu_265_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_pad_1_16_9_fu_265_ap_start_reg <= 1'b1;
        end else if ((grp_pad_1_16_9_fu_265_ap_ready == 1'b1)) begin
            grp_pad_1_16_9_fu_265_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        agg_result_V_0_i_reg_164 <= select_ln261_fu_352_p3;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        agg_result_V_0_i_reg_164 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        m_0_i_reg_152 <= m_reg_382;
    end else if (((grp_dense_512_256_s_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
        m_0_i_reg_152 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        max_id_V_reg_186 <= i_fu_368_p2;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        max_id_V_reg_186 <= 4'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        p_012_0_i_reg_176 <= select_ln261_1_fu_360_p3;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        p_012_0_i_reg_176 <= max_V_fu_327_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        m_reg_382 <= m_fu_296_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_flatten_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        reshaped_reg_374 <= grp_flatten_fu_247_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        signed1_reg_140 <= tmp_fu_317_p4;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state23) & (icmp_ln260_fu_331_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln260_fu_331_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln260_fu_331_p2 == 1'd1))) begin
        ap_return = agg_result_V_0_i_reg_164;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv1_address0 = grp_max_pool_16_16_s_fu_259_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        conv1_address0 = grp_conv_1_16_18_1_s_fu_241_output_r_address0;
    end else begin
        conv1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv1_ce0 = grp_max_pool_16_16_s_fu_259_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        conv1_ce0 = grp_conv_1_16_18_1_s_fu_241_output_r_ce0;
    end else begin
        conv1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv1_ce1 = grp_max_pool_16_16_s_fu_259_input_r_ce1;
    end else begin
        conv1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        conv1_pooled_address0 = grp_pad_16_8_s_fu_272_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        conv1_pooled_address0 = grp_max_pool_16_16_s_fu_259_output_r_address0;
    end else begin
        conv1_pooled_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        conv1_pooled_ce0 = grp_pad_16_8_s_fu_272_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        conv1_pooled_ce0 = grp_max_pool_16_16_s_fu_259_output_r_ce0;
    end else begin
        conv1_pooled_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv1_pooled_padded_address0 = grp_initialize_padded_me_fu_284_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        conv1_pooled_padded_address0 = grp_pad_16_8_s_fu_272_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        conv1_pooled_padded_address0 = grp_conv_16_32_10_4_s_fu_198_input_r_address0;
    end else begin
        conv1_pooled_padded_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv1_pooled_padded_ce0 = grp_initialize_padded_me_fu_284_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        conv1_pooled_padded_ce0 = grp_pad_16_8_s_fu_272_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        conv1_pooled_padded_ce0 = grp_conv_16_32_10_4_s_fu_198_input_r_ce0;
    end else begin
        conv1_pooled_padded_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv1_pooled_padded_d0 = grp_initialize_padded_me_fu_284_input_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        conv1_pooled_padded_d0 = grp_pad_16_8_s_fu_272_output_r_d0;
    end else begin
        conv1_pooled_padded_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        conv1_pooled_padded_we0 = grp_initialize_padded_me_fu_284_input_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        conv1_pooled_padded_we0 = grp_pad_16_8_s_fu_272_output_r_we0;
    end else begin
        conv1_pooled_padded_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        conv1_pooled_we0 = grp_max_pool_16_16_s_fu_259_output_r_we0;
    end else begin
        conv1_pooled_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        conv1_we0 = grp_conv_1_16_18_1_s_fu_241_output_r_we0;
    end else begin
        conv1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        conv2_address0 = grp_max_pool_32_8_s_fu_253_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        conv2_address0 = grp_conv_16_32_10_4_s_fu_198_output_r_address0;
    end else begin
        conv2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        conv2_ce0 = grp_max_pool_32_8_s_fu_253_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        conv2_ce0 = grp_conv_16_32_10_4_s_fu_198_output_r_ce0;
    end else begin
        conv2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        conv2_ce1 = grp_max_pool_32_8_s_fu_253_input_r_ce1;
    end else begin
        conv2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        conv2_pooled_address0 = grp_max_pool_32_8_s_fu_253_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        conv2_pooled_address0 = grp_flatten_fu_247_input_r_address0;
    end else begin
        conv2_pooled_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        conv2_pooled_ce0 = grp_max_pool_32_8_s_fu_253_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        conv2_pooled_ce0 = grp_flatten_fu_247_input_r_ce0;
    end else begin
        conv2_pooled_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        conv2_pooled_we0 = grp_max_pool_32_8_s_fu_253_output_r_we0;
    end else begin
        conv2_pooled_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        conv2_we0 = grp_conv_16_32_10_4_s_fu_198_output_r_we0;
    end else begin
        conv2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        dense1_V_address0 = zext_ln247_fu_302_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        dense1_V_address0 = grp_dense_512_256_s_fu_224_output_V_address0;
    end else begin
        dense1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        dense1_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        dense1_V_ce0 = grp_dense_512_256_s_fu_224_output_V_ce0;
    end else begin
        dense1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        dense1_V_we0 = grp_dense_512_256_s_fu_224_output_V_we0;
    end else begin
        dense1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        dense2_V_address0 = zext_ln261_fu_337_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        dense2_V_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        dense2_V_address0 = grp_dense_256_10_s_fu_232_output_V_address0;
    end else begin
        dense2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state23))) begin
        dense2_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        dense2_V_ce0 = grp_dense_256_10_s_fu_232_output_V_ce0;
    end else begin
        dense2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        dense2_V_we0 = grp_dense_256_10_s_fu_232_output_V_we0;
    end else begin
        dense2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_padded_address0 = grp_initialize_padded_me_1_fu_278_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_padded_address0 = grp_pad_1_16_9_fu_265_output_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_padded_address0 = grp_conv_1_16_18_1_s_fu_241_input_r_address0;
    end else begin
        input_padded_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_padded_ce0 = grp_initialize_padded_me_1_fu_278_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_padded_ce0 = grp_pad_1_16_9_fu_265_output_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_padded_ce0 = grp_conv_1_16_18_1_s_fu_241_input_r_ce0;
    end else begin
        input_padded_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_padded_d0 = grp_initialize_padded_me_1_fu_278_input_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_padded_d0 = grp_pad_1_16_9_fu_265_output_r_d0;
    end else begin
        input_padded_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_padded_we0 = grp_initialize_padded_me_1_fu_278_input_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_padded_we0 = grp_pad_1_16_9_fu_265_output_r_we0;
    end else begin
        input_padded_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_pad_1_16_9_fu_265_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_conv_1_16_18_1_s_fu_241_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_max_pool_16_16_s_fu_259_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_pad_16_8_s_fu_272_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_conv_16_32_10_4_s_fu_198_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_max_pool_32_8_s_fu_253_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_flatten_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((grp_dense_512_256_s_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln246_fu_290_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_dense_256_10_s_fu_232_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & (icmp_ln260_fu_331_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_initialize_padded_me_fu_284_ap_done == 1'b0) | (grp_initialize_padded_me_1_fu_278_ap_done == 1'b0));
end

assign grp_conv_16_32_10_4_s_fu_198_ap_start = grp_conv_16_32_10_4_s_fu_198_ap_start_reg;

assign grp_conv_1_16_18_1_s_fu_241_ap_start = grp_conv_1_16_18_1_s_fu_241_ap_start_reg;

assign grp_dense_256_10_s_fu_232_ap_start = grp_dense_256_10_s_fu_232_ap_start_reg;

assign grp_dense_512_256_s_fu_224_ap_start = grp_dense_512_256_s_fu_224_ap_start_reg;

assign grp_flatten_fu_247_ap_start = grp_flatten_fu_247_ap_start_reg;

assign grp_initialize_padded_me_1_fu_278_ap_start = grp_initialize_padded_me_1_fu_278_ap_start_reg;

assign grp_initialize_padded_me_fu_284_ap_start = grp_initialize_padded_me_fu_284_ap_start_reg;

assign grp_max_pool_16_16_s_fu_259_ap_start = grp_max_pool_16_16_s_fu_259_ap_start_reg;

assign grp_max_pool_32_8_s_fu_253_ap_start = grp_max_pool_32_8_s_fu_253_ap_start_reg;

assign grp_pad_16_8_s_fu_272_ap_start = grp_pad_16_8_s_fu_272_ap_start_reg;

assign grp_pad_1_16_9_fu_265_ap_start = grp_pad_1_16_9_fu_265_ap_start_reg;

assign i_fu_368_p2 = (max_id_V_reg_186 + 4'd1);

assign icmp_ln246_fu_290_p2 = ((m_0_i_reg_152 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln260_fu_331_p2 = ((max_id_V_reg_186 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln895_20_fu_346_p2 = (($signed(max_V_1_fu_342_p1) > $signed(p_012_0_i_reg_176)) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_307_p2 = (($signed(dense1_V_q0) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign input_r_address0 = grp_pad_1_16_9_fu_265_input_r_address0;

assign input_r_ce0 = grp_pad_1_16_9_fu_265_input_r_ce0;

assign m_fu_296_p2 = (m_0_i_reg_152 + 9'd1);

assign max_V_1_fu_342_p1 = $signed(dense2_V_q0);

assign max_V_fu_327_p1 = $signed(dense2_V_q0);

assign select_ln261_1_fu_360_p3 = ((icmp_ln895_20_fu_346_p2[0:0] === 1'b1) ? max_V_1_fu_342_p1 : p_012_0_i_reg_176);

assign select_ln261_fu_352_p3 = ((icmp_ln895_20_fu_346_p2[0:0] === 1'b1) ? max_id_V_reg_186 : agg_result_V_0_i_reg_164);

always @ (*) begin
    tmp_fu_317_p4 = signed1_reg_140;
    tmp_fu_317_p4[zext_ln247_1_fu_313_p1] = |(icmp_ln895_fu_307_p2);
end

assign zext_ln247_1_fu_313_p1 = m_0_i_reg_152;

assign zext_ln247_fu_302_p1 = m_0_i_reg_152;

assign zext_ln261_fu_337_p1 = max_id_V_reg_186;

endmodule //bnn_xcel
