// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module flatten (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [511:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] c_fu_97_p2;
reg   [5:0] c_reg_229;
wire    ap_CS_fsm_state2;
wire   [8:0] zext_ln230_fu_103_p1;
reg   [8:0] zext_ln230_reg_234;
wire   [0:0] icmp_ln226_fu_91_p2;
wire   [6:0] zext_ln230_1_fu_107_p1;
reg   [6:0] zext_ln230_1_reg_239;
wire   [2:0] y_fu_117_p2;
reg   [2:0] y_reg_247;
wire    ap_CS_fsm_state3;
wire   [5:0] zext_ln229_1_fu_131_p1;
reg   [5:0] zext_ln229_1_reg_252;
wire   [0:0] icmp_ln227_fu_111_p2;
wire   [3:0] shl_ln_fu_139_p3;
reg   [3:0] shl_ln_reg_257;
wire   [2:0] x_fu_153_p2;
reg   [2:0] x_reg_265;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln228_fu_147_p2;
wire   [8:0] add_ln230_fu_190_p2;
reg   [8:0] add_ln230_reg_275;
reg   [5:0] c_0_reg_55;
reg   [2:0] y_0_reg_66;
reg   [2:0] x_0_reg_77;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln230_3_fu_185_p1;
reg   [511:0] output_0_fu_38;
reg   [511:0] tmp_191_fu_205_p4;
wire   [4:0] tmp_s_fu_123_p3;
wire   [1:0] trunc_ln229_fu_135_p1;
wire   [3:0] zext_ln229_fu_159_p1;
wire   [3:0] add_ln229_fu_163_p2;
wire   [5:0] zext_ln230_2_fu_176_p1;
wire   [5:0] add_ln230_1_fu_180_p2;
wire   [8:0] shl_ln229_1_fu_168_p3;
wire   [10:0] zext_ln230_4_fu_202_p1;
wire   [0:0] tmp_fu_195_p3;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln227_fu_111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        c_0_reg_55 <= c_reg_229;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_0_reg_55 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        x_0_reg_77 <= x_reg_265;
    end else if (((icmp_ln227_fu_111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        x_0_reg_77 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln228_fu_147_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        y_0_reg_66 <= y_reg_247;
    end else if (((icmp_ln226_fu_91_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_0_reg_66 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln228_fu_147_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        add_ln230_reg_275 <= add_ln230_fu_190_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        c_reg_229 <= c_fu_97_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_0_fu_38 <= tmp_191_fu_205_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln227_fu_111_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        shl_ln_reg_257[3 : 2] <= shl_ln_fu_139_p3[3 : 2];
        zext_ln229_1_reg_252[4 : 2] <= zext_ln229_1_fu_131_p1[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        x_reg_265 <= x_fu_153_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        y_reg_247 <= y_fu_117_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln226_fu_91_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln230_1_reg_239[5 : 0] <= zext_ln230_1_fu_107_p1[5 : 0];
        zext_ln230_reg_234[5 : 0] <= zext_ln230_fu_103_p1[5 : 0];
    end
end

always @ (*) begin
    if ((((icmp_ln226_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln226_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln226_fu_91_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln227_fu_111_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln228_fu_147_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln229_fu_163_p2 = (zext_ln229_fu_159_p1 + shl_ln_reg_257);

assign add_ln230_1_fu_180_p2 = (zext_ln230_2_fu_176_p1 + zext_ln229_1_reg_252);

assign add_ln230_fu_190_p2 = (zext_ln230_reg_234 + shl_ln229_1_fu_168_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return = output_0_fu_38;

assign c_fu_97_p2 = (c_0_reg_55 + 6'd1);

assign icmp_ln226_fu_91_p2 = ((c_0_reg_55 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_111_p2 = ((y_0_reg_66 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln228_fu_147_p2 = ((x_0_reg_77 == 3'd4) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln230_3_fu_185_p1;

assign shl_ln229_1_fu_168_p3 = {{add_ln229_fu_163_p2}, {5'd0}};

assign shl_ln_fu_139_p3 = {{trunc_ln229_fu_135_p1}, {2'd0}};

always @ (*) begin
    tmp_191_fu_205_p4 = output_0_fu_38;
    tmp_191_fu_205_p4[zext_ln230_4_fu_202_p1] = |(tmp_fu_195_p3);
end

assign tmp_fu_195_p3 = input_r_q0[zext_ln230_1_reg_239];

assign tmp_s_fu_123_p3 = {{y_0_reg_66}, {2'd0}};

assign trunc_ln229_fu_135_p1 = y_0_reg_66[1:0];

assign x_fu_153_p2 = (x_0_reg_77 + 3'd1);

assign y_fu_117_p2 = (y_0_reg_66 + 3'd1);

assign zext_ln229_1_fu_131_p1 = tmp_s_fu_123_p3;

assign zext_ln229_fu_159_p1 = x_0_reg_77;

assign zext_ln230_1_fu_107_p1 = c_0_reg_55;

assign zext_ln230_2_fu_176_p1 = x_0_reg_77;

assign zext_ln230_3_fu_185_p1 = add_ln230_1_fu_180_p2;

assign zext_ln230_4_fu_202_p1 = add_ln230_reg_275;

assign zext_ln230_fu_103_p1 = c_0_reg_55;

always @ (posedge ap_clk) begin
    zext_ln230_reg_234[8:6] <= 3'b000;
    zext_ln230_1_reg_239[6] <= 1'b0;
    zext_ln229_1_reg_252[1:0] <= 2'b00;
    zext_ln229_1_reg_252[5] <= 1'b0;
    shl_ln_reg_257[1:0] <= 2'b00;
end

endmodule //flatten
