// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module max_pool_32_8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [5:0] input_r_address1;
output   input_r_ce1;
input  [31:0] input_r_q1;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] input_r_address0;
reg input_r_ce0;
reg[5:0] input_r_address1;
reg input_r_ce1;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [4:0] indvar_flatten_reg_170;
reg   [2:0] x_0_reg_181;
reg   [2:0] y_0_reg_192;
wire   [0:0] icmp_ln192_fu_203_p2;
reg   [0:0] icmp_ln192_reg_1951;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] add_ln192_fu_209_p2;
reg   [4:0] add_ln192_reg_1955;
reg    ap_enable_reg_pp0_iter0;
wire   [2:0] select_ln205_fu_227_p3;
reg   [2:0] select_ln205_reg_1960;
wire   [2:0] select_ln205_1_fu_235_p3;
reg   [2:0] select_ln205_1_reg_1966;
wire   [1:0] trunc_ln205_1_fu_247_p1;
reg   [1:0] trunc_ln205_1_reg_1973;
wire   [2:0] or_ln205_fu_274_p2;
reg   [2:0] or_ln205_reg_1983;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] input_load_reg_1998;
reg   [31:0] input_load_1_reg_2039;
wire   [2:0] y_fu_332_p2;
reg   [2:0] y_reg_2075;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage1_subdone;
reg   [4:0] ap_phi_mux_indvar_flatten_phi_fu_174_p4;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_x_0_phi_fu_185_p4;
reg   [2:0] ap_phi_mux_y_0_phi_fu_196_p4;
wire   [63:0] zext_ln205_1_fu_269_p1;
wire   [63:0] zext_ln205_3_fu_290_p1;
wire   [63:0] zext_ln205_2_fu_315_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln205_4_fu_327_p1;
wire   [63:0] zext_ln212_1_fu_1877_p1;
wire   [0:0] icmp_ln193_fu_221_p2;
wire   [2:0] x_fu_215_p2;
wire   [1:0] trunc_ln205_fu_243_p1;
wire   [5:0] tmp_s_fu_257_p5;
wire   [2:0] shl_ln205_1_fu_251_p2;
wire   [5:0] tmp_33_fu_280_p4;
wire   [2:0] shl_ln205_fu_295_p2;
wire   [2:0] or_ln205_1_fu_300_p2;
wire   [5:0] tmp_1_fu_306_p4;
wire   [5:0] tmp_34_fu_320_p3;
wire   [0:0] trunc_ln205_2_fu_340_p1;
wire   [0:0] trunc_ln205_3_fu_560_p1;
wire   [0:0] trunc_ln205_4_fu_780_p1;
wire   [0:0] trunc_ln205_5_fu_1032_p1;
wire   [0:0] or_ln205_3_fu_1042_p2;
wire   [0:0] or_ln205_2_fu_1036_p2;
wire   [0:0] tmp_2_fu_343_p3;
wire   [0:0] tmp_35_fu_563_p3;
wire   [0:0] tmp_66_fu_784_p3;
wire   [0:0] tmp_97_fu_1054_p3;
wire   [0:0] or_ln205_6_fu_1068_p2;
wire   [0:0] or_ln205_5_fu_1062_p2;
wire   [0:0] tmp_3_fu_350_p3;
wire   [0:0] tmp_36_fu_570_p3;
wire   [0:0] tmp_67_fu_792_p3;
wire   [0:0] tmp_98_fu_1080_p3;
wire   [0:0] or_ln205_9_fu_1094_p2;
wire   [0:0] or_ln205_8_fu_1088_p2;
wire   [0:0] tmp_4_fu_357_p3;
wire   [0:0] tmp_37_fu_577_p3;
wire   [0:0] tmp_68_fu_800_p3;
wire   [0:0] tmp_99_fu_1106_p3;
wire   [0:0] or_ln205_12_fu_1120_p2;
wire   [0:0] or_ln205_11_fu_1114_p2;
wire   [0:0] tmp_5_fu_364_p3;
wire   [0:0] tmp_38_fu_584_p3;
wire   [0:0] tmp_69_fu_808_p3;
wire   [0:0] tmp_100_fu_1132_p3;
wire   [0:0] or_ln205_15_fu_1146_p2;
wire   [0:0] or_ln205_14_fu_1140_p2;
wire   [0:0] tmp_6_fu_371_p3;
wire   [0:0] tmp_39_fu_591_p3;
wire   [0:0] tmp_70_fu_816_p3;
wire   [0:0] tmp_101_fu_1158_p3;
wire   [0:0] or_ln205_18_fu_1172_p2;
wire   [0:0] or_ln205_17_fu_1166_p2;
wire   [0:0] tmp_7_fu_378_p3;
wire   [0:0] tmp_40_fu_598_p3;
wire   [0:0] tmp_71_fu_824_p3;
wire   [0:0] tmp_102_fu_1184_p3;
wire   [0:0] or_ln205_21_fu_1198_p2;
wire   [0:0] or_ln205_20_fu_1192_p2;
wire   [0:0] tmp_8_fu_385_p3;
wire   [0:0] tmp_41_fu_605_p3;
wire   [0:0] tmp_72_fu_832_p3;
wire   [0:0] tmp_103_fu_1210_p3;
wire   [0:0] or_ln205_24_fu_1224_p2;
wire   [0:0] or_ln205_23_fu_1218_p2;
wire   [0:0] tmp_9_fu_392_p3;
wire   [0:0] tmp_42_fu_612_p3;
wire   [0:0] tmp_73_fu_840_p3;
wire   [0:0] tmp_104_fu_1236_p3;
wire   [0:0] or_ln205_27_fu_1250_p2;
wire   [0:0] or_ln205_26_fu_1244_p2;
wire   [0:0] tmp_10_fu_399_p3;
wire   [0:0] tmp_43_fu_619_p3;
wire   [0:0] tmp_74_fu_848_p3;
wire   [0:0] tmp_105_fu_1262_p3;
wire   [0:0] or_ln205_30_fu_1276_p2;
wire   [0:0] or_ln205_29_fu_1270_p2;
wire   [0:0] tmp_11_fu_406_p3;
wire   [0:0] tmp_44_fu_626_p3;
wire   [0:0] tmp_75_fu_856_p3;
wire   [0:0] tmp_106_fu_1288_p3;
wire   [0:0] or_ln205_33_fu_1302_p2;
wire   [0:0] or_ln205_32_fu_1296_p2;
wire   [0:0] tmp_12_fu_413_p3;
wire   [0:0] tmp_45_fu_633_p3;
wire   [0:0] tmp_76_fu_864_p3;
wire   [0:0] tmp_107_fu_1314_p3;
wire   [0:0] or_ln205_36_fu_1328_p2;
wire   [0:0] or_ln205_35_fu_1322_p2;
wire   [0:0] tmp_13_fu_420_p3;
wire   [0:0] tmp_46_fu_640_p3;
wire   [0:0] tmp_77_fu_872_p3;
wire   [0:0] tmp_108_fu_1340_p3;
wire   [0:0] or_ln205_39_fu_1354_p2;
wire   [0:0] or_ln205_38_fu_1348_p2;
wire   [0:0] tmp_14_fu_427_p3;
wire   [0:0] tmp_47_fu_647_p3;
wire   [0:0] tmp_78_fu_880_p3;
wire   [0:0] tmp_109_fu_1366_p3;
wire   [0:0] or_ln205_42_fu_1380_p2;
wire   [0:0] or_ln205_41_fu_1374_p2;
wire   [0:0] tmp_15_fu_434_p3;
wire   [0:0] tmp_48_fu_654_p3;
wire   [0:0] tmp_79_fu_888_p3;
wire   [0:0] tmp_110_fu_1392_p3;
wire   [0:0] or_ln205_45_fu_1406_p2;
wire   [0:0] or_ln205_44_fu_1400_p2;
wire   [0:0] tmp_16_fu_441_p3;
wire   [0:0] tmp_49_fu_661_p3;
wire   [0:0] tmp_80_fu_896_p3;
wire   [0:0] tmp_111_fu_1418_p3;
wire   [0:0] or_ln205_48_fu_1432_p2;
wire   [0:0] or_ln205_47_fu_1426_p2;
wire   [0:0] tmp_17_fu_448_p3;
wire   [0:0] tmp_50_fu_668_p3;
wire   [0:0] tmp_81_fu_904_p3;
wire   [0:0] tmp_112_fu_1444_p3;
wire   [0:0] or_ln205_51_fu_1458_p2;
wire   [0:0] or_ln205_50_fu_1452_p2;
wire   [0:0] tmp_18_fu_455_p3;
wire   [0:0] tmp_51_fu_675_p3;
wire   [0:0] tmp_82_fu_912_p3;
wire   [0:0] tmp_113_fu_1470_p3;
wire   [0:0] or_ln205_54_fu_1484_p2;
wire   [0:0] or_ln205_53_fu_1478_p2;
wire   [0:0] tmp_19_fu_462_p3;
wire   [0:0] tmp_52_fu_682_p3;
wire   [0:0] tmp_83_fu_920_p3;
wire   [0:0] tmp_114_fu_1496_p3;
wire   [0:0] or_ln205_57_fu_1510_p2;
wire   [0:0] or_ln205_56_fu_1504_p2;
wire   [0:0] tmp_20_fu_469_p3;
wire   [0:0] tmp_53_fu_689_p3;
wire   [0:0] tmp_84_fu_928_p3;
wire   [0:0] tmp_115_fu_1522_p3;
wire   [0:0] or_ln205_60_fu_1536_p2;
wire   [0:0] or_ln205_59_fu_1530_p2;
wire   [0:0] tmp_21_fu_476_p3;
wire   [0:0] tmp_54_fu_696_p3;
wire   [0:0] tmp_85_fu_936_p3;
wire   [0:0] tmp_116_fu_1548_p3;
wire   [0:0] or_ln205_63_fu_1562_p2;
wire   [0:0] or_ln205_62_fu_1556_p2;
wire   [0:0] tmp_22_fu_483_p3;
wire   [0:0] tmp_55_fu_703_p3;
wire   [0:0] tmp_86_fu_944_p3;
wire   [0:0] tmp_117_fu_1574_p3;
wire   [0:0] or_ln205_66_fu_1588_p2;
wire   [0:0] or_ln205_65_fu_1582_p2;
wire   [0:0] tmp_23_fu_490_p3;
wire   [0:0] tmp_56_fu_710_p3;
wire   [0:0] tmp_87_fu_952_p3;
wire   [0:0] tmp_118_fu_1600_p3;
wire   [0:0] or_ln205_69_fu_1614_p2;
wire   [0:0] or_ln205_68_fu_1608_p2;
wire   [0:0] tmp_24_fu_497_p3;
wire   [0:0] tmp_57_fu_717_p3;
wire   [0:0] tmp_88_fu_960_p3;
wire   [0:0] tmp_119_fu_1626_p3;
wire   [0:0] or_ln205_72_fu_1640_p2;
wire   [0:0] or_ln205_71_fu_1634_p2;
wire   [0:0] tmp_25_fu_504_p3;
wire   [0:0] tmp_58_fu_724_p3;
wire   [0:0] tmp_89_fu_968_p3;
wire   [0:0] tmp_120_fu_1652_p3;
wire   [0:0] or_ln205_75_fu_1666_p2;
wire   [0:0] or_ln205_74_fu_1660_p2;
wire   [0:0] tmp_26_fu_511_p3;
wire   [0:0] tmp_59_fu_731_p3;
wire   [0:0] tmp_90_fu_976_p3;
wire   [0:0] tmp_121_fu_1678_p3;
wire   [0:0] or_ln205_78_fu_1692_p2;
wire   [0:0] or_ln205_77_fu_1686_p2;
wire   [0:0] tmp_27_fu_518_p3;
wire   [0:0] tmp_60_fu_738_p3;
wire   [0:0] tmp_91_fu_984_p3;
wire   [0:0] tmp_122_fu_1704_p3;
wire   [0:0] or_ln205_81_fu_1718_p2;
wire   [0:0] or_ln205_80_fu_1712_p2;
wire   [0:0] tmp_28_fu_525_p3;
wire   [0:0] tmp_61_fu_745_p3;
wire   [0:0] tmp_92_fu_992_p3;
wire   [0:0] tmp_123_fu_1730_p3;
wire   [0:0] or_ln205_84_fu_1744_p2;
wire   [0:0] or_ln205_83_fu_1738_p2;
wire   [0:0] tmp_29_fu_532_p3;
wire   [0:0] tmp_62_fu_752_p3;
wire   [0:0] tmp_93_fu_1000_p3;
wire   [0:0] tmp_124_fu_1756_p3;
wire   [0:0] or_ln205_87_fu_1770_p2;
wire   [0:0] or_ln205_86_fu_1764_p2;
wire   [0:0] tmp_30_fu_539_p3;
wire   [0:0] tmp_63_fu_759_p3;
wire   [0:0] tmp_94_fu_1008_p3;
wire   [0:0] tmp_125_fu_1782_p3;
wire   [0:0] or_ln205_90_fu_1796_p2;
wire   [0:0] or_ln205_89_fu_1790_p2;
wire   [0:0] tmp_31_fu_546_p3;
wire   [0:0] tmp_64_fu_766_p3;
wire   [0:0] tmp_95_fu_1016_p3;
wire   [0:0] tmp_126_fu_1808_p3;
wire   [0:0] or_ln205_93_fu_1822_p2;
wire   [0:0] or_ln205_92_fu_1816_p2;
wire   [0:0] tmp_32_fu_553_p3;
wire   [0:0] tmp_65_fu_773_p3;
wire   [0:0] tmp_96_fu_1024_p3;
wire   [0:0] tmp_127_fu_1834_p3;
wire   [0:0] or_ln205_96_fu_1848_p2;
wire   [0:0] or_ln205_95_fu_1842_p2;
wire   [4:0] tmp_129_fu_1860_p3;
wire   [5:0] zext_ln205_fu_337_p1;
wire   [5:0] zext_ln212_fu_1867_p1;
wire   [5:0] add_ln212_fu_1871_p2;
wire   [0:0] or_ln205_97_fu_1854_p2;
wire   [0:0] or_ln205_94_fu_1828_p2;
wire   [0:0] or_ln205_91_fu_1802_p2;
wire   [0:0] or_ln205_88_fu_1776_p2;
wire   [0:0] or_ln205_85_fu_1750_p2;
wire   [0:0] or_ln205_82_fu_1724_p2;
wire   [0:0] or_ln205_79_fu_1698_p2;
wire   [0:0] or_ln205_76_fu_1672_p2;
wire   [0:0] or_ln205_73_fu_1646_p2;
wire   [0:0] or_ln205_70_fu_1620_p2;
wire   [0:0] or_ln205_67_fu_1594_p2;
wire   [0:0] or_ln205_64_fu_1568_p2;
wire   [0:0] or_ln205_61_fu_1542_p2;
wire   [0:0] or_ln205_58_fu_1516_p2;
wire   [0:0] or_ln205_55_fu_1490_p2;
wire   [0:0] or_ln205_52_fu_1464_p2;
wire   [0:0] or_ln205_49_fu_1438_p2;
wire   [0:0] or_ln205_46_fu_1412_p2;
wire   [0:0] or_ln205_43_fu_1386_p2;
wire   [0:0] or_ln205_40_fu_1360_p2;
wire   [0:0] or_ln205_37_fu_1334_p2;
wire   [0:0] or_ln205_34_fu_1308_p2;
wire   [0:0] or_ln205_31_fu_1282_p2;
wire   [0:0] or_ln205_28_fu_1256_p2;
wire   [0:0] or_ln205_25_fu_1230_p2;
wire   [0:0] or_ln205_22_fu_1204_p2;
wire   [0:0] or_ln205_19_fu_1178_p2;
wire   [0:0] or_ln205_16_fu_1152_p2;
wire   [0:0] or_ln205_13_fu_1126_p2;
wire   [0:0] or_ln205_10_fu_1100_p2;
wire   [0:0] or_ln205_7_fu_1074_p2;
wire   [0:0] or_ln205_4_fu_1048_p2;
wire    ap_CS_fsm_state5;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        indvar_flatten_reg_170 <= add_ln192_reg_1955;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_170 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        x_0_reg_181 <= select_ln205_1_reg_1966;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_0_reg_181 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y_0_reg_192 <= y_reg_2075;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_0_reg_192 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln192_reg_1955 <= add_ln192_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln192_reg_1951 <= icmp_ln192_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        input_load_1_reg_2039 <= input_r_q1;
        input_load_reg_1998 <= input_r_q0;
        y_reg_2075 <= y_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_fu_203_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln205_reg_1983[2 : 1] <= or_ln205_fu_274_p2[2 : 1];
        select_ln205_reg_1960 <= select_ln205_fu_227_p3;
        trunc_ln205_1_reg_1973 <= trunc_ln205_1_fu_247_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_fu_203_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln205_1_reg_1966 <= select_ln205_1_fu_235_p3;
    end
end

always @ (*) begin
    if ((icmp_ln192_fu_203_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_174_p4 = add_ln192_reg_1955;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_174_p4 = indvar_flatten_reg_170;
    end
end

always @ (*) begin
    if (((icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_x_0_phi_fu_185_p4 = select_ln205_1_reg_1966;
    end else begin
        ap_phi_mux_x_0_phi_fu_185_p4 = x_0_reg_181;
    end
end

always @ (*) begin
    if (((icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_y_0_phi_fu_196_p4 = y_reg_2075;
    end else begin
        ap_phi_mux_y_0_phi_fu_196_p4 = y_0_reg_192;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            input_r_address0 = zext_ln205_2_fu_315_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            input_r_address0 = zext_ln205_1_fu_269_p1;
        end else begin
            input_r_address0 = 'bx;
        end
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            input_r_address1 = zext_ln205_4_fu_327_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            input_r_address1 = zext_ln205_3_fu_290_p1;
        end else begin
            input_r_address1 = 'bx;
        end
    end else begin
        input_r_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        input_r_ce1 = 1'b1;
    end else begin
        input_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1951 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln192_fu_203_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln192_fu_203_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln192_fu_209_p2 = (ap_phi_mux_indvar_flatten_phi_fu_174_p4 + 5'd1);

assign add_ln212_fu_1871_p2 = (zext_ln205_fu_337_p1 + zext_ln212_fu_1867_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign icmp_ln192_fu_203_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_174_p4 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_221_p2 = ((ap_phi_mux_y_0_phi_fu_196_p4 == 3'd4) ? 1'b1 : 1'b0);

assign or_ln205_10_fu_1100_p2 = (or_ln205_9_fu_1094_p2 | or_ln205_8_fu_1088_p2);

assign or_ln205_11_fu_1114_p2 = (tmp_4_fu_357_p3 | tmp_37_fu_577_p3);

assign or_ln205_12_fu_1120_p2 = (tmp_99_fu_1106_p3 | tmp_68_fu_800_p3);

assign or_ln205_13_fu_1126_p2 = (or_ln205_12_fu_1120_p2 | or_ln205_11_fu_1114_p2);

assign or_ln205_14_fu_1140_p2 = (tmp_5_fu_364_p3 | tmp_38_fu_584_p3);

assign or_ln205_15_fu_1146_p2 = (tmp_69_fu_808_p3 | tmp_100_fu_1132_p3);

assign or_ln205_16_fu_1152_p2 = (or_ln205_15_fu_1146_p2 | or_ln205_14_fu_1140_p2);

assign or_ln205_17_fu_1166_p2 = (tmp_6_fu_371_p3 | tmp_39_fu_591_p3);

assign or_ln205_18_fu_1172_p2 = (tmp_70_fu_816_p3 | tmp_101_fu_1158_p3);

assign or_ln205_19_fu_1178_p2 = (or_ln205_18_fu_1172_p2 | or_ln205_17_fu_1166_p2);

assign or_ln205_1_fu_300_p2 = (shl_ln205_fu_295_p2 | 3'd1);

assign or_ln205_20_fu_1192_p2 = (tmp_7_fu_378_p3 | tmp_40_fu_598_p3);

assign or_ln205_21_fu_1198_p2 = (tmp_71_fu_824_p3 | tmp_102_fu_1184_p3);

assign or_ln205_22_fu_1204_p2 = (or_ln205_21_fu_1198_p2 | or_ln205_20_fu_1192_p2);

assign or_ln205_23_fu_1218_p2 = (tmp_8_fu_385_p3 | tmp_41_fu_605_p3);

assign or_ln205_24_fu_1224_p2 = (tmp_72_fu_832_p3 | tmp_103_fu_1210_p3);

assign or_ln205_25_fu_1230_p2 = (or_ln205_24_fu_1224_p2 | or_ln205_23_fu_1218_p2);

assign or_ln205_26_fu_1244_p2 = (tmp_9_fu_392_p3 | tmp_42_fu_612_p3);

assign or_ln205_27_fu_1250_p2 = (tmp_73_fu_840_p3 | tmp_104_fu_1236_p3);

assign or_ln205_28_fu_1256_p2 = (or_ln205_27_fu_1250_p2 | or_ln205_26_fu_1244_p2);

assign or_ln205_29_fu_1270_p2 = (tmp_43_fu_619_p3 | tmp_10_fu_399_p3);

assign or_ln205_2_fu_1036_p2 = (trunc_ln205_3_fu_560_p1 | trunc_ln205_2_fu_340_p1);

assign or_ln205_30_fu_1276_p2 = (tmp_74_fu_848_p3 | tmp_105_fu_1262_p3);

assign or_ln205_31_fu_1282_p2 = (or_ln205_30_fu_1276_p2 | or_ln205_29_fu_1270_p2);

assign or_ln205_32_fu_1296_p2 = (tmp_44_fu_626_p3 | tmp_11_fu_406_p3);

assign or_ln205_33_fu_1302_p2 = (tmp_75_fu_856_p3 | tmp_106_fu_1288_p3);

assign or_ln205_34_fu_1308_p2 = (or_ln205_33_fu_1302_p2 | or_ln205_32_fu_1296_p2);

assign or_ln205_35_fu_1322_p2 = (tmp_45_fu_633_p3 | tmp_12_fu_413_p3);

assign or_ln205_36_fu_1328_p2 = (tmp_76_fu_864_p3 | tmp_107_fu_1314_p3);

assign or_ln205_37_fu_1334_p2 = (or_ln205_36_fu_1328_p2 | or_ln205_35_fu_1322_p2);

assign or_ln205_38_fu_1348_p2 = (tmp_46_fu_640_p3 | tmp_13_fu_420_p3);

assign or_ln205_39_fu_1354_p2 = (tmp_77_fu_872_p3 | tmp_108_fu_1340_p3);

assign or_ln205_3_fu_1042_p2 = (trunc_ln205_5_fu_1032_p1 | trunc_ln205_4_fu_780_p1);

assign or_ln205_40_fu_1360_p2 = (or_ln205_39_fu_1354_p2 | or_ln205_38_fu_1348_p2);

assign or_ln205_41_fu_1374_p2 = (tmp_47_fu_647_p3 | tmp_14_fu_427_p3);

assign or_ln205_42_fu_1380_p2 = (tmp_78_fu_880_p3 | tmp_109_fu_1366_p3);

assign or_ln205_43_fu_1386_p2 = (or_ln205_42_fu_1380_p2 | or_ln205_41_fu_1374_p2);

assign or_ln205_44_fu_1400_p2 = (tmp_48_fu_654_p3 | tmp_15_fu_434_p3);

assign or_ln205_45_fu_1406_p2 = (tmp_79_fu_888_p3 | tmp_110_fu_1392_p3);

assign or_ln205_46_fu_1412_p2 = (or_ln205_45_fu_1406_p2 | or_ln205_44_fu_1400_p2);

assign or_ln205_47_fu_1426_p2 = (tmp_49_fu_661_p3 | tmp_16_fu_441_p3);

assign or_ln205_48_fu_1432_p2 = (tmp_80_fu_896_p3 | tmp_111_fu_1418_p3);

assign or_ln205_49_fu_1438_p2 = (or_ln205_48_fu_1432_p2 | or_ln205_47_fu_1426_p2);

assign or_ln205_4_fu_1048_p2 = (or_ln205_3_fu_1042_p2 | or_ln205_2_fu_1036_p2);

assign or_ln205_50_fu_1452_p2 = (tmp_50_fu_668_p3 | tmp_17_fu_448_p3);

assign or_ln205_51_fu_1458_p2 = (tmp_81_fu_904_p3 | tmp_112_fu_1444_p3);

assign or_ln205_52_fu_1464_p2 = (or_ln205_51_fu_1458_p2 | or_ln205_50_fu_1452_p2);

assign or_ln205_53_fu_1478_p2 = (tmp_51_fu_675_p3 | tmp_18_fu_455_p3);

assign or_ln205_54_fu_1484_p2 = (tmp_82_fu_912_p3 | tmp_113_fu_1470_p3);

assign or_ln205_55_fu_1490_p2 = (or_ln205_54_fu_1484_p2 | or_ln205_53_fu_1478_p2);

assign or_ln205_56_fu_1504_p2 = (tmp_52_fu_682_p3 | tmp_19_fu_462_p3);

assign or_ln205_57_fu_1510_p2 = (tmp_83_fu_920_p3 | tmp_114_fu_1496_p3);

assign or_ln205_58_fu_1516_p2 = (or_ln205_57_fu_1510_p2 | or_ln205_56_fu_1504_p2);

assign or_ln205_59_fu_1530_p2 = (tmp_53_fu_689_p3 | tmp_20_fu_469_p3);

assign or_ln205_5_fu_1062_p2 = (tmp_35_fu_563_p3 | tmp_2_fu_343_p3);

assign or_ln205_60_fu_1536_p2 = (tmp_84_fu_928_p3 | tmp_115_fu_1522_p3);

assign or_ln205_61_fu_1542_p2 = (or_ln205_60_fu_1536_p2 | or_ln205_59_fu_1530_p2);

assign or_ln205_62_fu_1556_p2 = (tmp_54_fu_696_p3 | tmp_21_fu_476_p3);

assign or_ln205_63_fu_1562_p2 = (tmp_85_fu_936_p3 | tmp_116_fu_1548_p3);

assign or_ln205_64_fu_1568_p2 = (or_ln205_63_fu_1562_p2 | or_ln205_62_fu_1556_p2);

assign or_ln205_65_fu_1582_p2 = (tmp_55_fu_703_p3 | tmp_22_fu_483_p3);

assign or_ln205_66_fu_1588_p2 = (tmp_86_fu_944_p3 | tmp_117_fu_1574_p3);

assign or_ln205_67_fu_1594_p2 = (or_ln205_66_fu_1588_p2 | or_ln205_65_fu_1582_p2);

assign or_ln205_68_fu_1608_p2 = (tmp_56_fu_710_p3 | tmp_23_fu_490_p3);

assign or_ln205_69_fu_1614_p2 = (tmp_87_fu_952_p3 | tmp_118_fu_1600_p3);

assign or_ln205_6_fu_1068_p2 = (tmp_97_fu_1054_p3 | tmp_66_fu_784_p3);

assign or_ln205_70_fu_1620_p2 = (or_ln205_69_fu_1614_p2 | or_ln205_68_fu_1608_p2);

assign or_ln205_71_fu_1634_p2 = (tmp_57_fu_717_p3 | tmp_24_fu_497_p3);

assign or_ln205_72_fu_1640_p2 = (tmp_88_fu_960_p3 | tmp_119_fu_1626_p3);

assign or_ln205_73_fu_1646_p2 = (or_ln205_72_fu_1640_p2 | or_ln205_71_fu_1634_p2);

assign or_ln205_74_fu_1660_p2 = (tmp_58_fu_724_p3 | tmp_25_fu_504_p3);

assign or_ln205_75_fu_1666_p2 = (tmp_89_fu_968_p3 | tmp_120_fu_1652_p3);

assign or_ln205_76_fu_1672_p2 = (or_ln205_75_fu_1666_p2 | or_ln205_74_fu_1660_p2);

assign or_ln205_77_fu_1686_p2 = (tmp_59_fu_731_p3 | tmp_26_fu_511_p3);

assign or_ln205_78_fu_1692_p2 = (tmp_90_fu_976_p3 | tmp_121_fu_1678_p3);

assign or_ln205_79_fu_1698_p2 = (or_ln205_78_fu_1692_p2 | or_ln205_77_fu_1686_p2);

assign or_ln205_7_fu_1074_p2 = (or_ln205_6_fu_1068_p2 | or_ln205_5_fu_1062_p2);

assign or_ln205_80_fu_1712_p2 = (tmp_60_fu_738_p3 | tmp_27_fu_518_p3);

assign or_ln205_81_fu_1718_p2 = (tmp_91_fu_984_p3 | tmp_122_fu_1704_p3);

assign or_ln205_82_fu_1724_p2 = (or_ln205_81_fu_1718_p2 | or_ln205_80_fu_1712_p2);

assign or_ln205_83_fu_1738_p2 = (tmp_61_fu_745_p3 | tmp_28_fu_525_p3);

assign or_ln205_84_fu_1744_p2 = (tmp_92_fu_992_p3 | tmp_123_fu_1730_p3);

assign or_ln205_85_fu_1750_p2 = (or_ln205_84_fu_1744_p2 | or_ln205_83_fu_1738_p2);

assign or_ln205_86_fu_1764_p2 = (tmp_62_fu_752_p3 | tmp_29_fu_532_p3);

assign or_ln205_87_fu_1770_p2 = (tmp_93_fu_1000_p3 | tmp_124_fu_1756_p3);

assign or_ln205_88_fu_1776_p2 = (or_ln205_87_fu_1770_p2 | or_ln205_86_fu_1764_p2);

assign or_ln205_89_fu_1790_p2 = (tmp_63_fu_759_p3 | tmp_30_fu_539_p3);

assign or_ln205_8_fu_1088_p2 = (tmp_3_fu_350_p3 | tmp_36_fu_570_p3);

assign or_ln205_90_fu_1796_p2 = (tmp_94_fu_1008_p3 | tmp_125_fu_1782_p3);

assign or_ln205_91_fu_1802_p2 = (or_ln205_90_fu_1796_p2 | or_ln205_89_fu_1790_p2);

assign or_ln205_92_fu_1816_p2 = (tmp_64_fu_766_p3 | tmp_31_fu_546_p3);

assign or_ln205_93_fu_1822_p2 = (tmp_95_fu_1016_p3 | tmp_126_fu_1808_p3);

assign or_ln205_94_fu_1828_p2 = (or_ln205_93_fu_1822_p2 | or_ln205_92_fu_1816_p2);

assign or_ln205_95_fu_1842_p2 = (tmp_65_fu_773_p3 | tmp_32_fu_553_p3);

assign or_ln205_96_fu_1848_p2 = (tmp_96_fu_1024_p3 | tmp_127_fu_1834_p3);

assign or_ln205_97_fu_1854_p2 = (or_ln205_96_fu_1848_p2 | or_ln205_95_fu_1842_p2);

assign or_ln205_9_fu_1094_p2 = (tmp_98_fu_1080_p3 | tmp_67_fu_792_p3);

assign or_ln205_fu_274_p2 = (shl_ln205_1_fu_251_p2 | 3'd1);

assign output_r_address0 = zext_ln212_1_fu_1877_p1;

assign output_r_d0 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{or_ln205_97_fu_1854_p2}, {or_ln205_94_fu_1828_p2}}, {or_ln205_91_fu_1802_p2}}, {or_ln205_88_fu_1776_p2}}, {or_ln205_85_fu_1750_p2}}, {or_ln205_82_fu_1724_p2}}, {or_ln205_79_fu_1698_p2}}, {or_ln205_76_fu_1672_p2}}, {or_ln205_73_fu_1646_p2}}, {or_ln205_70_fu_1620_p2}}, {or_ln205_67_fu_1594_p2}}, {or_ln205_64_fu_1568_p2}}, {or_ln205_61_fu_1542_p2}}, {or_ln205_58_fu_1516_p2}}, {or_ln205_55_fu_1490_p2}}, {or_ln205_52_fu_1464_p2}}, {or_ln205_49_fu_1438_p2}}, {or_ln205_46_fu_1412_p2}}, {or_ln205_43_fu_1386_p2}}, {or_ln205_40_fu_1360_p2}}, {or_ln205_37_fu_1334_p2}}, {or_ln205_34_fu_1308_p2}}, {or_ln205_31_fu_1282_p2}}, {or_ln205_28_fu_1256_p2}}, {or_ln205_25_fu_1230_p2}}, {or_ln205_22_fu_1204_p2}}, {or_ln205_19_fu_1178_p2}}, {or_ln205_16_fu_1152_p2}}, {or_ln205_13_fu_1126_p2}}, {or_ln205_10_fu_1100_p2}}, {or_ln205_7_fu_1074_p2}}, {or_ln205_4_fu_1048_p2}};

assign select_ln205_1_fu_235_p3 = ((icmp_ln193_fu_221_p2[0:0] === 1'b1) ? x_fu_215_p2 : ap_phi_mux_x_0_phi_fu_185_p4);

assign select_ln205_fu_227_p3 = ((icmp_ln193_fu_221_p2[0:0] === 1'b1) ? 3'd0 : ap_phi_mux_y_0_phi_fu_196_p4);

assign shl_ln205_1_fu_251_p2 = select_ln205_fu_227_p3 << 3'd1;

assign shl_ln205_fu_295_p2 = select_ln205_1_reg_1966 << 3'd1;

assign tmp_100_fu_1132_p3 = input_r_q1[32'd4];

assign tmp_101_fu_1158_p3 = input_r_q1[32'd5];

assign tmp_102_fu_1184_p3 = input_r_q1[32'd6];

assign tmp_103_fu_1210_p3 = input_r_q1[32'd7];

assign tmp_104_fu_1236_p3 = input_r_q1[32'd8];

assign tmp_105_fu_1262_p3 = input_r_q1[32'd9];

assign tmp_106_fu_1288_p3 = input_r_q1[32'd10];

assign tmp_107_fu_1314_p3 = input_r_q1[32'd11];

assign tmp_108_fu_1340_p3 = input_r_q1[32'd12];

assign tmp_109_fu_1366_p3 = input_r_q1[32'd13];

assign tmp_10_fu_399_p3 = input_load_reg_1998[32'd9];

assign tmp_110_fu_1392_p3 = input_r_q1[32'd14];

assign tmp_111_fu_1418_p3 = input_r_q1[32'd15];

assign tmp_112_fu_1444_p3 = input_r_q1[32'd16];

assign tmp_113_fu_1470_p3 = input_r_q1[32'd17];

assign tmp_114_fu_1496_p3 = input_r_q1[32'd18];

assign tmp_115_fu_1522_p3 = input_r_q1[32'd19];

assign tmp_116_fu_1548_p3 = input_r_q1[32'd20];

assign tmp_117_fu_1574_p3 = input_r_q1[32'd21];

assign tmp_118_fu_1600_p3 = input_r_q1[32'd22];

assign tmp_119_fu_1626_p3 = input_r_q1[32'd23];

assign tmp_11_fu_406_p3 = input_load_reg_1998[32'd10];

assign tmp_120_fu_1652_p3 = input_r_q1[32'd24];

assign tmp_121_fu_1678_p3 = input_r_q1[32'd25];

assign tmp_122_fu_1704_p3 = input_r_q1[32'd26];

assign tmp_123_fu_1730_p3 = input_r_q1[32'd27];

assign tmp_124_fu_1756_p3 = input_r_q1[32'd28];

assign tmp_125_fu_1782_p3 = input_r_q1[32'd29];

assign tmp_126_fu_1808_p3 = input_r_q1[32'd30];

assign tmp_127_fu_1834_p3 = input_r_q1[32'd31];

assign tmp_129_fu_1860_p3 = {{select_ln205_reg_1960}, {2'd0}};

assign tmp_12_fu_413_p3 = input_load_reg_1998[32'd11];

assign tmp_13_fu_420_p3 = input_load_reg_1998[32'd12];

assign tmp_14_fu_427_p3 = input_load_reg_1998[32'd13];

assign tmp_15_fu_434_p3 = input_load_reg_1998[32'd14];

assign tmp_16_fu_441_p3 = input_load_reg_1998[32'd15];

assign tmp_17_fu_448_p3 = input_load_reg_1998[32'd16];

assign tmp_18_fu_455_p3 = input_load_reg_1998[32'd17];

assign tmp_19_fu_462_p3 = input_load_reg_1998[32'd18];

assign tmp_1_fu_306_p4 = {{{trunc_ln205_1_reg_1973}, {1'd0}}, {or_ln205_1_fu_300_p2}};

assign tmp_20_fu_469_p3 = input_load_reg_1998[32'd19];

assign tmp_21_fu_476_p3 = input_load_reg_1998[32'd20];

assign tmp_22_fu_483_p3 = input_load_reg_1998[32'd21];

assign tmp_23_fu_490_p3 = input_load_reg_1998[32'd22];

assign tmp_24_fu_497_p3 = input_load_reg_1998[32'd23];

assign tmp_25_fu_504_p3 = input_load_reg_1998[32'd24];

assign tmp_26_fu_511_p3 = input_load_reg_1998[32'd25];

assign tmp_27_fu_518_p3 = input_load_reg_1998[32'd26];

assign tmp_28_fu_525_p3 = input_load_reg_1998[32'd27];

assign tmp_29_fu_532_p3 = input_load_reg_1998[32'd28];

assign tmp_2_fu_343_p3 = input_load_reg_1998[32'd1];

assign tmp_30_fu_539_p3 = input_load_reg_1998[32'd29];

assign tmp_31_fu_546_p3 = input_load_reg_1998[32'd30];

assign tmp_32_fu_553_p3 = input_load_reg_1998[32'd31];

assign tmp_33_fu_280_p4 = {{{or_ln205_fu_274_p2}, {trunc_ln205_fu_243_p1}}, {1'd0}};

assign tmp_34_fu_320_p3 = {{or_ln205_reg_1983}, {or_ln205_1_fu_300_p2}};

assign tmp_35_fu_563_p3 = input_load_1_reg_2039[32'd1];

assign tmp_36_fu_570_p3 = input_load_1_reg_2039[32'd2];

assign tmp_37_fu_577_p3 = input_load_1_reg_2039[32'd3];

assign tmp_38_fu_584_p3 = input_load_1_reg_2039[32'd4];

assign tmp_39_fu_591_p3 = input_load_1_reg_2039[32'd5];

assign tmp_3_fu_350_p3 = input_load_reg_1998[32'd2];

assign tmp_40_fu_598_p3 = input_load_1_reg_2039[32'd6];

assign tmp_41_fu_605_p3 = input_load_1_reg_2039[32'd7];

assign tmp_42_fu_612_p3 = input_load_1_reg_2039[32'd8];

assign tmp_43_fu_619_p3 = input_load_1_reg_2039[32'd9];

assign tmp_44_fu_626_p3 = input_load_1_reg_2039[32'd10];

assign tmp_45_fu_633_p3 = input_load_1_reg_2039[32'd11];

assign tmp_46_fu_640_p3 = input_load_1_reg_2039[32'd12];

assign tmp_47_fu_647_p3 = input_load_1_reg_2039[32'd13];

assign tmp_48_fu_654_p3 = input_load_1_reg_2039[32'd14];

assign tmp_49_fu_661_p3 = input_load_1_reg_2039[32'd15];

assign tmp_4_fu_357_p3 = input_load_reg_1998[32'd3];

assign tmp_50_fu_668_p3 = input_load_1_reg_2039[32'd16];

assign tmp_51_fu_675_p3 = input_load_1_reg_2039[32'd17];

assign tmp_52_fu_682_p3 = input_load_1_reg_2039[32'd18];

assign tmp_53_fu_689_p3 = input_load_1_reg_2039[32'd19];

assign tmp_54_fu_696_p3 = input_load_1_reg_2039[32'd20];

assign tmp_55_fu_703_p3 = input_load_1_reg_2039[32'd21];

assign tmp_56_fu_710_p3 = input_load_1_reg_2039[32'd22];

assign tmp_57_fu_717_p3 = input_load_1_reg_2039[32'd23];

assign tmp_58_fu_724_p3 = input_load_1_reg_2039[32'd24];

assign tmp_59_fu_731_p3 = input_load_1_reg_2039[32'd25];

assign tmp_5_fu_364_p3 = input_load_reg_1998[32'd4];

assign tmp_60_fu_738_p3 = input_load_1_reg_2039[32'd26];

assign tmp_61_fu_745_p3 = input_load_1_reg_2039[32'd27];

assign tmp_62_fu_752_p3 = input_load_1_reg_2039[32'd28];

assign tmp_63_fu_759_p3 = input_load_1_reg_2039[32'd29];

assign tmp_64_fu_766_p3 = input_load_1_reg_2039[32'd30];

assign tmp_65_fu_773_p3 = input_load_1_reg_2039[32'd31];

assign tmp_66_fu_784_p3 = input_r_q0[32'd1];

assign tmp_67_fu_792_p3 = input_r_q0[32'd2];

assign tmp_68_fu_800_p3 = input_r_q0[32'd3];

assign tmp_69_fu_808_p3 = input_r_q0[32'd4];

assign tmp_6_fu_371_p3 = input_load_reg_1998[32'd5];

assign tmp_70_fu_816_p3 = input_r_q0[32'd5];

assign tmp_71_fu_824_p3 = input_r_q0[32'd6];

assign tmp_72_fu_832_p3 = input_r_q0[32'd7];

assign tmp_73_fu_840_p3 = input_r_q0[32'd8];

assign tmp_74_fu_848_p3 = input_r_q0[32'd9];

assign tmp_75_fu_856_p3 = input_r_q0[32'd10];

assign tmp_76_fu_864_p3 = input_r_q0[32'd11];

assign tmp_77_fu_872_p3 = input_r_q0[32'd12];

assign tmp_78_fu_880_p3 = input_r_q0[32'd13];

assign tmp_79_fu_888_p3 = input_r_q0[32'd14];

assign tmp_7_fu_378_p3 = input_load_reg_1998[32'd6];

assign tmp_80_fu_896_p3 = input_r_q0[32'd15];

assign tmp_81_fu_904_p3 = input_r_q0[32'd16];

assign tmp_82_fu_912_p3 = input_r_q0[32'd17];

assign tmp_83_fu_920_p3 = input_r_q0[32'd18];

assign tmp_84_fu_928_p3 = input_r_q0[32'd19];

assign tmp_85_fu_936_p3 = input_r_q0[32'd20];

assign tmp_86_fu_944_p3 = input_r_q0[32'd21];

assign tmp_87_fu_952_p3 = input_r_q0[32'd22];

assign tmp_88_fu_960_p3 = input_r_q0[32'd23];

assign tmp_89_fu_968_p3 = input_r_q0[32'd24];

assign tmp_8_fu_385_p3 = input_load_reg_1998[32'd7];

assign tmp_90_fu_976_p3 = input_r_q0[32'd25];

assign tmp_91_fu_984_p3 = input_r_q0[32'd26];

assign tmp_92_fu_992_p3 = input_r_q0[32'd27];

assign tmp_93_fu_1000_p3 = input_r_q0[32'd28];

assign tmp_94_fu_1008_p3 = input_r_q0[32'd29];

assign tmp_95_fu_1016_p3 = input_r_q0[32'd30];

assign tmp_96_fu_1024_p3 = input_r_q0[32'd31];

assign tmp_97_fu_1054_p3 = input_r_q1[32'd1];

assign tmp_98_fu_1080_p3 = input_r_q1[32'd2];

assign tmp_99_fu_1106_p3 = input_r_q1[32'd3];

assign tmp_9_fu_392_p3 = input_load_reg_1998[32'd8];

assign tmp_s_fu_257_p5 = {{{{trunc_ln205_1_fu_247_p1}, {1'd0}}, {trunc_ln205_fu_243_p1}}, {1'd0}};

assign trunc_ln205_1_fu_247_p1 = select_ln205_fu_227_p3[1:0];

assign trunc_ln205_2_fu_340_p1 = input_load_reg_1998[0:0];

assign trunc_ln205_3_fu_560_p1 = input_load_1_reg_2039[0:0];

assign trunc_ln205_4_fu_780_p1 = input_r_q0[0:0];

assign trunc_ln205_5_fu_1032_p1 = input_r_q1[0:0];

assign trunc_ln205_fu_243_p1 = select_ln205_1_fu_235_p3[1:0];

assign x_fu_215_p2 = (3'd1 + ap_phi_mux_x_0_phi_fu_185_p4);

assign y_fu_332_p2 = (3'd1 + select_ln205_reg_1960);

assign zext_ln205_1_fu_269_p1 = tmp_s_fu_257_p5;

assign zext_ln205_2_fu_315_p1 = tmp_1_fu_306_p4;

assign zext_ln205_3_fu_290_p1 = tmp_33_fu_280_p4;

assign zext_ln205_4_fu_327_p1 = tmp_34_fu_320_p3;

assign zext_ln205_fu_337_p1 = select_ln205_1_reg_1966;

assign zext_ln212_1_fu_1877_p1 = add_ln212_fu_1871_p2;

assign zext_ln212_fu_1867_p1 = tmp_129_fu_1860_p3;

always @ (posedge ap_clk) begin
    or_ln205_reg_1983[0] <= 1'b1;
end

endmodule //max_pool_32_8_s
