// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module max_pool_16_16_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_pp0_stage0 = 4'd2;
parameter    ap_ST_fsm_pp0_stage1 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [7:0] input_r_address1;
output   input_r_ce1;
input  [15:0] input_r_q1;
output  [5:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] input_r_address0;
reg input_r_ce0;
reg[7:0] input_r_address1;
reg input_r_ce1;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [6:0] indvar_flatten_reg_138;
reg   [3:0] x_0_reg_149;
reg   [3:0] y_0_reg_160;
wire   [0:0] icmp_ln192_fu_171_p2;
reg   [0:0] icmp_ln192_reg_1119;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] add_ln192_fu_177_p2;
reg   [6:0] add_ln192_reg_1123;
reg    ap_enable_reg_pp0_iter0;
wire   [3:0] select_ln205_fu_195_p3;
reg   [3:0] select_ln205_reg_1128;
wire   [3:0] select_ln205_2_fu_203_p3;
reg   [3:0] select_ln205_2_reg_1134;
wire   [2:0] trunc_ln205_6_fu_215_p1;
reg   [2:0] trunc_ln205_6_reg_1141;
wire   [3:0] or_ln205_fu_242_p2;
reg   [3:0] or_ln205_reg_1151;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] input_load_reg_1166;
reg   [15:0] input_load_4_reg_1191;
wire   [3:0] y_fu_300_p2;
reg   [3:0] y_reg_1211;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage1_subdone;
reg   [6:0] ap_phi_mux_indvar_flatten_phi_fu_142_p4;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_x_0_phi_fu_153_p4;
reg   [3:0] ap_phi_mux_y_0_phi_fu_164_p4;
wire   [63:0] zext_ln205_5_fu_237_p1;
wire   [63:0] zext_ln205_7_fu_258_p1;
wire   [63:0] zext_ln205_6_fu_283_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln205_8_fu_295_p1;
wire   [63:0] zext_ln212_2_fu_1077_p1;
wire   [0:0] icmp_ln193_fu_189_p2;
wire   [3:0] x_fu_183_p2;
wire   [2:0] trunc_ln205_fu_211_p1;
wire   [7:0] tmp_s_fu_225_p5;
wire   [3:0] shl_ln205_2_fu_219_p2;
wire   [7:0] tmp_144_fu_248_p4;
wire   [3:0] shl_ln205_fu_263_p2;
wire   [3:0] or_ln205_98_fu_268_p2;
wire   [7:0] tmp_130_fu_274_p4;
wire   [7:0] tmp_145_fu_288_p3;
wire   [0:0] trunc_ln205_7_fu_308_p1;
wire   [0:0] trunc_ln205_8_fu_416_p1;
wire   [0:0] trunc_ln205_9_fu_524_p1;
wire   [0:0] trunc_ln205_10_fu_648_p1;
wire   [0:0] or_ln205_100_fu_658_p2;
wire   [0:0] or_ln205_99_fu_652_p2;
wire   [0:0] tmp_128_fu_311_p3;
wire   [0:0] tmp_146_fu_419_p3;
wire   [0:0] tmp_161_fu_528_p3;
wire   [0:0] tmp_176_fu_670_p3;
wire   [0:0] or_ln205_103_fu_684_p2;
wire   [0:0] or_ln205_102_fu_678_p2;
wire   [0:0] tmp_129_fu_318_p3;
wire   [0:0] tmp_147_fu_426_p3;
wire   [0:0] tmp_162_fu_536_p3;
wire   [0:0] tmp_177_fu_696_p3;
wire   [0:0] or_ln205_106_fu_710_p2;
wire   [0:0] or_ln205_105_fu_704_p2;
wire   [0:0] tmp_131_fu_325_p3;
wire   [0:0] tmp_148_fu_433_p3;
wire   [0:0] tmp_163_fu_544_p3;
wire   [0:0] tmp_178_fu_722_p3;
wire   [0:0] or_ln205_109_fu_736_p2;
wire   [0:0] or_ln205_108_fu_730_p2;
wire   [0:0] tmp_132_fu_332_p3;
wire   [0:0] tmp_149_fu_440_p3;
wire   [0:0] tmp_164_fu_552_p3;
wire   [0:0] tmp_179_fu_748_p3;
wire   [0:0] or_ln205_112_fu_762_p2;
wire   [0:0] or_ln205_111_fu_756_p2;
wire   [0:0] tmp_133_fu_339_p3;
wire   [0:0] tmp_150_fu_447_p3;
wire   [0:0] tmp_165_fu_560_p3;
wire   [0:0] tmp_180_fu_774_p3;
wire   [0:0] or_ln205_115_fu_788_p2;
wire   [0:0] or_ln205_114_fu_782_p2;
wire   [0:0] tmp_134_fu_346_p3;
wire   [0:0] tmp_151_fu_454_p3;
wire   [0:0] tmp_166_fu_568_p3;
wire   [0:0] tmp_181_fu_800_p3;
wire   [0:0] or_ln205_118_fu_814_p2;
wire   [0:0] or_ln205_117_fu_808_p2;
wire   [0:0] tmp_135_fu_353_p3;
wire   [0:0] tmp_152_fu_461_p3;
wire   [0:0] tmp_167_fu_576_p3;
wire   [0:0] tmp_182_fu_826_p3;
wire   [0:0] or_ln205_121_fu_840_p2;
wire   [0:0] or_ln205_120_fu_834_p2;
wire   [0:0] tmp_136_fu_360_p3;
wire   [0:0] tmp_153_fu_468_p3;
wire   [0:0] tmp_168_fu_584_p3;
wire   [0:0] tmp_183_fu_852_p3;
wire   [0:0] or_ln205_124_fu_866_p2;
wire   [0:0] or_ln205_123_fu_860_p2;
wire   [0:0] tmp_137_fu_367_p3;
wire   [0:0] tmp_154_fu_475_p3;
wire   [0:0] tmp_169_fu_592_p3;
wire   [0:0] tmp_184_fu_878_p3;
wire   [0:0] or_ln205_127_fu_892_p2;
wire   [0:0] or_ln205_126_fu_886_p2;
wire   [0:0] tmp_138_fu_374_p3;
wire   [0:0] tmp_155_fu_482_p3;
wire   [0:0] tmp_170_fu_600_p3;
wire   [0:0] tmp_185_fu_904_p3;
wire   [0:0] or_ln205_130_fu_918_p2;
wire   [0:0] or_ln205_129_fu_912_p2;
wire   [0:0] tmp_139_fu_381_p3;
wire   [0:0] tmp_156_fu_489_p3;
wire   [0:0] tmp_171_fu_608_p3;
wire   [0:0] tmp_186_fu_930_p3;
wire   [0:0] or_ln205_133_fu_944_p2;
wire   [0:0] or_ln205_132_fu_938_p2;
wire   [0:0] tmp_140_fu_388_p3;
wire   [0:0] tmp_157_fu_496_p3;
wire   [0:0] tmp_172_fu_616_p3;
wire   [0:0] tmp_187_fu_956_p3;
wire   [0:0] or_ln205_136_fu_970_p2;
wire   [0:0] or_ln205_135_fu_964_p2;
wire   [0:0] tmp_141_fu_395_p3;
wire   [0:0] tmp_158_fu_503_p3;
wire   [0:0] tmp_173_fu_624_p3;
wire   [0:0] tmp_188_fu_982_p3;
wire   [0:0] or_ln205_139_fu_996_p2;
wire   [0:0] or_ln205_138_fu_990_p2;
wire   [0:0] tmp_142_fu_402_p3;
wire   [0:0] tmp_159_fu_510_p3;
wire   [0:0] tmp_174_fu_632_p3;
wire   [0:0] tmp_189_fu_1008_p3;
wire   [0:0] or_ln205_142_fu_1022_p2;
wire   [0:0] or_ln205_141_fu_1016_p2;
wire   [0:0] tmp_143_fu_409_p3;
wire   [0:0] tmp_160_fu_517_p3;
wire   [0:0] tmp_175_fu_640_p3;
wire   [0:0] tmp_190_fu_1034_p3;
wire   [0:0] or_ln205_145_fu_1048_p2;
wire   [0:0] or_ln205_144_fu_1042_p2;
wire   [6:0] tmp_191_fu_1060_p3;
wire   [7:0] zext_ln205_fu_305_p1;
wire   [7:0] zext_ln212_fu_1067_p1;
wire   [7:0] add_ln212_fu_1071_p2;
wire   [0:0] or_ln205_146_fu_1054_p2;
wire   [0:0] or_ln205_143_fu_1028_p2;
wire   [0:0] or_ln205_140_fu_1002_p2;
wire   [0:0] or_ln205_137_fu_976_p2;
wire   [0:0] or_ln205_134_fu_950_p2;
wire   [0:0] or_ln205_131_fu_924_p2;
wire   [0:0] or_ln205_128_fu_898_p2;
wire   [0:0] or_ln205_125_fu_872_p2;
wire   [0:0] or_ln205_122_fu_846_p2;
wire   [0:0] or_ln205_119_fu_820_p2;
wire   [0:0] or_ln205_116_fu_794_p2;
wire   [0:0] or_ln205_113_fu_768_p2;
wire   [0:0] or_ln205_110_fu_742_p2;
wire   [0:0] or_ln205_107_fu_716_p2;
wire   [0:0] or_ln205_104_fu_690_p2;
wire   [0:0] or_ln205_101_fu_664_p2;
wire    ap_CS_fsm_state5;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        indvar_flatten_reg_138 <= add_ln192_reg_1123;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_138 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        x_0_reg_149 <= select_ln205_2_reg_1134;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_0_reg_149 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y_0_reg_160 <= y_reg_1211;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_0_reg_160 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln192_reg_1123 <= add_ln192_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln192_reg_1119 <= icmp_ln192_fu_171_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        input_load_4_reg_1191 <= input_r_q1;
        input_load_reg_1166 <= input_r_q0;
        y_reg_1211 <= y_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        or_ln205_reg_1151[3 : 1] <= or_ln205_fu_242_p2[3 : 1];
        select_ln205_reg_1128 <= select_ln205_fu_195_p3;
        trunc_ln205_6_reg_1141 <= trunc_ln205_6_fu_215_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_fu_171_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln205_2_reg_1134 <= select_ln205_2_fu_203_p3;
    end
end

always @ (*) begin
    if ((icmp_ln192_fu_171_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_142_p4 = add_ln192_reg_1123;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_142_p4 = indvar_flatten_reg_138;
    end
end

always @ (*) begin
    if (((icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_x_0_phi_fu_153_p4 = select_ln205_2_reg_1134;
    end else begin
        ap_phi_mux_x_0_phi_fu_153_p4 = x_0_reg_149;
    end
end

always @ (*) begin
    if (((icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_y_0_phi_fu_164_p4 = y_reg_1211;
    end else begin
        ap_phi_mux_y_0_phi_fu_164_p4 = y_0_reg_160;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            input_r_address0 = zext_ln205_6_fu_283_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            input_r_address0 = zext_ln205_5_fu_237_p1;
        end else begin
            input_r_address0 = 'bx;
        end
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            input_r_address1 = zext_ln205_8_fu_295_p1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            input_r_address1 = zext_ln205_7_fu_258_p1;
        end else begin
            input_r_address1 = 'bx;
        end
    end else begin
        input_r_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        input_r_ce1 = 1'b1;
    end else begin
        input_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln192_reg_1119 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln192_fu_171_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((icmp_ln192_fu_171_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln192_fu_177_p2 = (ap_phi_mux_indvar_flatten_phi_fu_142_p4 + 7'd1);

assign add_ln212_fu_1071_p2 = (zext_ln205_fu_305_p1 + zext_ln212_fu_1067_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign icmp_ln192_fu_171_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_142_p4 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_189_p2 = ((ap_phi_mux_y_0_phi_fu_164_p4 == 4'd8) ? 1'b1 : 1'b0);

assign or_ln205_100_fu_658_p2 = (trunc_ln205_9_fu_524_p1 | trunc_ln205_10_fu_648_p1);

assign or_ln205_101_fu_664_p2 = (or_ln205_99_fu_652_p2 | or_ln205_100_fu_658_p2);

assign or_ln205_102_fu_678_p2 = (tmp_146_fu_419_p3 | tmp_128_fu_311_p3);

assign or_ln205_103_fu_684_p2 = (tmp_176_fu_670_p3 | tmp_161_fu_528_p3);

assign or_ln205_104_fu_690_p2 = (or_ln205_103_fu_684_p2 | or_ln205_102_fu_678_p2);

assign or_ln205_105_fu_704_p2 = (tmp_147_fu_426_p3 | tmp_129_fu_318_p3);

assign or_ln205_106_fu_710_p2 = (tmp_177_fu_696_p3 | tmp_162_fu_536_p3);

assign or_ln205_107_fu_716_p2 = (or_ln205_106_fu_710_p2 | or_ln205_105_fu_704_p2);

assign or_ln205_108_fu_730_p2 = (tmp_148_fu_433_p3 | tmp_131_fu_325_p3);

assign or_ln205_109_fu_736_p2 = (tmp_178_fu_722_p3 | tmp_163_fu_544_p3);

assign or_ln205_110_fu_742_p2 = (or_ln205_109_fu_736_p2 | or_ln205_108_fu_730_p2);

assign or_ln205_111_fu_756_p2 = (tmp_149_fu_440_p3 | tmp_132_fu_332_p3);

assign or_ln205_112_fu_762_p2 = (tmp_179_fu_748_p3 | tmp_164_fu_552_p3);

assign or_ln205_113_fu_768_p2 = (or_ln205_112_fu_762_p2 | or_ln205_111_fu_756_p2);

assign or_ln205_114_fu_782_p2 = (tmp_150_fu_447_p3 | tmp_133_fu_339_p3);

assign or_ln205_115_fu_788_p2 = (tmp_180_fu_774_p3 | tmp_165_fu_560_p3);

assign or_ln205_116_fu_794_p2 = (or_ln205_115_fu_788_p2 | or_ln205_114_fu_782_p2);

assign or_ln205_117_fu_808_p2 = (tmp_151_fu_454_p3 | tmp_134_fu_346_p3);

assign or_ln205_118_fu_814_p2 = (tmp_181_fu_800_p3 | tmp_166_fu_568_p3);

assign or_ln205_119_fu_820_p2 = (or_ln205_118_fu_814_p2 | or_ln205_117_fu_808_p2);

assign or_ln205_120_fu_834_p2 = (tmp_152_fu_461_p3 | tmp_135_fu_353_p3);

assign or_ln205_121_fu_840_p2 = (tmp_182_fu_826_p3 | tmp_167_fu_576_p3);

assign or_ln205_122_fu_846_p2 = (or_ln205_121_fu_840_p2 | or_ln205_120_fu_834_p2);

assign or_ln205_123_fu_860_p2 = (tmp_153_fu_468_p3 | tmp_136_fu_360_p3);

assign or_ln205_124_fu_866_p2 = (tmp_183_fu_852_p3 | tmp_168_fu_584_p3);

assign or_ln205_125_fu_872_p2 = (or_ln205_124_fu_866_p2 | or_ln205_123_fu_860_p2);

assign or_ln205_126_fu_886_p2 = (tmp_154_fu_475_p3 | tmp_137_fu_367_p3);

assign or_ln205_127_fu_892_p2 = (tmp_184_fu_878_p3 | tmp_169_fu_592_p3);

assign or_ln205_128_fu_898_p2 = (or_ln205_127_fu_892_p2 | or_ln205_126_fu_886_p2);

assign or_ln205_129_fu_912_p2 = (tmp_155_fu_482_p3 | tmp_138_fu_374_p3);

assign or_ln205_130_fu_918_p2 = (tmp_185_fu_904_p3 | tmp_170_fu_600_p3);

assign or_ln205_131_fu_924_p2 = (or_ln205_130_fu_918_p2 | or_ln205_129_fu_912_p2);

assign or_ln205_132_fu_938_p2 = (tmp_156_fu_489_p3 | tmp_139_fu_381_p3);

assign or_ln205_133_fu_944_p2 = (tmp_186_fu_930_p3 | tmp_171_fu_608_p3);

assign or_ln205_134_fu_950_p2 = (or_ln205_133_fu_944_p2 | or_ln205_132_fu_938_p2);

assign or_ln205_135_fu_964_p2 = (tmp_157_fu_496_p3 | tmp_140_fu_388_p3);

assign or_ln205_136_fu_970_p2 = (tmp_187_fu_956_p3 | tmp_172_fu_616_p3);

assign or_ln205_137_fu_976_p2 = (or_ln205_136_fu_970_p2 | or_ln205_135_fu_964_p2);

assign or_ln205_138_fu_990_p2 = (tmp_158_fu_503_p3 | tmp_141_fu_395_p3);

assign or_ln205_139_fu_996_p2 = (tmp_188_fu_982_p3 | tmp_173_fu_624_p3);

assign or_ln205_140_fu_1002_p2 = (or_ln205_139_fu_996_p2 | or_ln205_138_fu_990_p2);

assign or_ln205_141_fu_1016_p2 = (tmp_159_fu_510_p3 | tmp_142_fu_402_p3);

assign or_ln205_142_fu_1022_p2 = (tmp_189_fu_1008_p3 | tmp_174_fu_632_p3);

assign or_ln205_143_fu_1028_p2 = (or_ln205_142_fu_1022_p2 | or_ln205_141_fu_1016_p2);

assign or_ln205_144_fu_1042_p2 = (tmp_160_fu_517_p3 | tmp_143_fu_409_p3);

assign or_ln205_145_fu_1048_p2 = (tmp_190_fu_1034_p3 | tmp_175_fu_640_p3);

assign or_ln205_146_fu_1054_p2 = (or_ln205_145_fu_1048_p2 | or_ln205_144_fu_1042_p2);

assign or_ln205_98_fu_268_p2 = (shl_ln205_fu_263_p2 | 4'd1);

assign or_ln205_99_fu_652_p2 = (trunc_ln205_8_fu_416_p1 | trunc_ln205_7_fu_308_p1);

assign or_ln205_fu_242_p2 = (shl_ln205_2_fu_219_p2 | 4'd1);

assign output_r_address0 = zext_ln212_2_fu_1077_p1;

assign output_r_d0 = {{{{{{{{{{{{{{{{or_ln205_146_fu_1054_p2}, {or_ln205_143_fu_1028_p2}}, {or_ln205_140_fu_1002_p2}}, {or_ln205_137_fu_976_p2}}, {or_ln205_134_fu_950_p2}}, {or_ln205_131_fu_924_p2}}, {or_ln205_128_fu_898_p2}}, {or_ln205_125_fu_872_p2}}, {or_ln205_122_fu_846_p2}}, {or_ln205_119_fu_820_p2}}, {or_ln205_116_fu_794_p2}}, {or_ln205_113_fu_768_p2}}, {or_ln205_110_fu_742_p2}}, {or_ln205_107_fu_716_p2}}, {or_ln205_104_fu_690_p2}}, {or_ln205_101_fu_664_p2}};

assign select_ln205_2_fu_203_p3 = ((icmp_ln193_fu_189_p2[0:0] === 1'b1) ? x_fu_183_p2 : ap_phi_mux_x_0_phi_fu_153_p4);

assign select_ln205_fu_195_p3 = ((icmp_ln193_fu_189_p2[0:0] === 1'b1) ? 4'd0 : ap_phi_mux_y_0_phi_fu_164_p4);

assign shl_ln205_2_fu_219_p2 = select_ln205_fu_195_p3 << 4'd1;

assign shl_ln205_fu_263_p2 = select_ln205_2_reg_1134 << 4'd1;

assign tmp_128_fu_311_p3 = input_load_reg_1166[32'd1];

assign tmp_129_fu_318_p3 = input_load_reg_1166[32'd2];

assign tmp_130_fu_274_p4 = {{{trunc_ln205_6_reg_1141}, {1'd0}}, {or_ln205_98_fu_268_p2}};

assign tmp_131_fu_325_p3 = input_load_reg_1166[32'd3];

assign tmp_132_fu_332_p3 = input_load_reg_1166[32'd4];

assign tmp_133_fu_339_p3 = input_load_reg_1166[32'd5];

assign tmp_134_fu_346_p3 = input_load_reg_1166[32'd6];

assign tmp_135_fu_353_p3 = input_load_reg_1166[32'd7];

assign tmp_136_fu_360_p3 = input_load_reg_1166[32'd8];

assign tmp_137_fu_367_p3 = input_load_reg_1166[32'd9];

assign tmp_138_fu_374_p3 = input_load_reg_1166[32'd10];

assign tmp_139_fu_381_p3 = input_load_reg_1166[32'd11];

assign tmp_140_fu_388_p3 = input_load_reg_1166[32'd12];

assign tmp_141_fu_395_p3 = input_load_reg_1166[32'd13];

assign tmp_142_fu_402_p3 = input_load_reg_1166[32'd14];

assign tmp_143_fu_409_p3 = input_load_reg_1166[32'd15];

assign tmp_144_fu_248_p4 = {{{or_ln205_fu_242_p2}, {trunc_ln205_fu_211_p1}}, {1'd0}};

assign tmp_145_fu_288_p3 = {{or_ln205_reg_1151}, {or_ln205_98_fu_268_p2}};

assign tmp_146_fu_419_p3 = input_load_4_reg_1191[32'd1];

assign tmp_147_fu_426_p3 = input_load_4_reg_1191[32'd2];

assign tmp_148_fu_433_p3 = input_load_4_reg_1191[32'd3];

assign tmp_149_fu_440_p3 = input_load_4_reg_1191[32'd4];

assign tmp_150_fu_447_p3 = input_load_4_reg_1191[32'd5];

assign tmp_151_fu_454_p3 = input_load_4_reg_1191[32'd6];

assign tmp_152_fu_461_p3 = input_load_4_reg_1191[32'd7];

assign tmp_153_fu_468_p3 = input_load_4_reg_1191[32'd8];

assign tmp_154_fu_475_p3 = input_load_4_reg_1191[32'd9];

assign tmp_155_fu_482_p3 = input_load_4_reg_1191[32'd10];

assign tmp_156_fu_489_p3 = input_load_4_reg_1191[32'd11];

assign tmp_157_fu_496_p3 = input_load_4_reg_1191[32'd12];

assign tmp_158_fu_503_p3 = input_load_4_reg_1191[32'd13];

assign tmp_159_fu_510_p3 = input_load_4_reg_1191[32'd14];

assign tmp_160_fu_517_p3 = input_load_4_reg_1191[32'd15];

assign tmp_161_fu_528_p3 = input_r_q0[32'd1];

assign tmp_162_fu_536_p3 = input_r_q0[32'd2];

assign tmp_163_fu_544_p3 = input_r_q0[32'd3];

assign tmp_164_fu_552_p3 = input_r_q0[32'd4];

assign tmp_165_fu_560_p3 = input_r_q0[32'd5];

assign tmp_166_fu_568_p3 = input_r_q0[32'd6];

assign tmp_167_fu_576_p3 = input_r_q0[32'd7];

assign tmp_168_fu_584_p3 = input_r_q0[32'd8];

assign tmp_169_fu_592_p3 = input_r_q0[32'd9];

assign tmp_170_fu_600_p3 = input_r_q0[32'd10];

assign tmp_171_fu_608_p3 = input_r_q0[32'd11];

assign tmp_172_fu_616_p3 = input_r_q0[32'd12];

assign tmp_173_fu_624_p3 = input_r_q0[32'd13];

assign tmp_174_fu_632_p3 = input_r_q0[32'd14];

assign tmp_175_fu_640_p3 = input_r_q0[32'd15];

assign tmp_176_fu_670_p3 = input_r_q1[32'd1];

assign tmp_177_fu_696_p3 = input_r_q1[32'd2];

assign tmp_178_fu_722_p3 = input_r_q1[32'd3];

assign tmp_179_fu_748_p3 = input_r_q1[32'd4];

assign tmp_180_fu_774_p3 = input_r_q1[32'd5];

assign tmp_181_fu_800_p3 = input_r_q1[32'd6];

assign tmp_182_fu_826_p3 = input_r_q1[32'd7];

assign tmp_183_fu_852_p3 = input_r_q1[32'd8];

assign tmp_184_fu_878_p3 = input_r_q1[32'd9];

assign tmp_185_fu_904_p3 = input_r_q1[32'd10];

assign tmp_186_fu_930_p3 = input_r_q1[32'd11];

assign tmp_187_fu_956_p3 = input_r_q1[32'd12];

assign tmp_188_fu_982_p3 = input_r_q1[32'd13];

assign tmp_189_fu_1008_p3 = input_r_q1[32'd14];

assign tmp_190_fu_1034_p3 = input_r_q1[32'd15];

assign tmp_191_fu_1060_p3 = {{select_ln205_reg_1128}, {3'd0}};

assign tmp_s_fu_225_p5 = {{{{trunc_ln205_6_fu_215_p1}, {1'd0}}, {trunc_ln205_fu_211_p1}}, {1'd0}};

assign trunc_ln205_10_fu_648_p1 = input_r_q1[0:0];

assign trunc_ln205_6_fu_215_p1 = select_ln205_fu_195_p3[2:0];

assign trunc_ln205_7_fu_308_p1 = input_load_reg_1166[0:0];

assign trunc_ln205_8_fu_416_p1 = input_load_4_reg_1191[0:0];

assign trunc_ln205_9_fu_524_p1 = input_r_q0[0:0];

assign trunc_ln205_fu_211_p1 = select_ln205_2_fu_203_p3[2:0];

assign x_fu_183_p2 = (4'd1 + ap_phi_mux_x_0_phi_fu_153_p4);

assign y_fu_300_p2 = (4'd1 + select_ln205_reg_1128);

assign zext_ln205_5_fu_237_p1 = tmp_s_fu_225_p5;

assign zext_ln205_6_fu_283_p1 = tmp_130_fu_274_p4;

assign zext_ln205_7_fu_258_p1 = tmp_144_fu_248_p4;

assign zext_ln205_8_fu_295_p1 = tmp_145_fu_288_p3;

assign zext_ln205_fu_305_p1 = select_ln205_2_reg_1134;

assign zext_ln212_2_fu_1077_p1 = add_ln212_fu_1071_p2;

assign zext_ln212_fu_1067_p1 = tmp_191_fu_1060_p3;

always @ (posedge ap_clk) begin
    or_ln205_reg_1151[0] <= 1'b1;
end

endmodule //max_pool_16_16_s
