// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pad_1_16_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] input_r_address0;
output   input_r_ce0;
input  [0:0] input_r_q0;
output  [8:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [0:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [8:0] indvar_flatten_reg_75;
reg   [4:0] x_0_reg_86;
reg   [4:0] y_0_reg_97;
wire   [0:0] icmp_ln28_fu_114_p2;
reg   [0:0] icmp_ln28_reg_239;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] add_ln28_fu_120_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [4:0] select_ln32_3_fu_140_p3;
reg   [4:0] select_ln32_3_reg_248;
wire   [4:0] y_fu_193_p2;
reg   [4:0] y_reg_258;
wire   [9:0] add_ln32_8_fu_229_p2;
reg   [9:0] add_ln32_8_reg_263;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg   [4:0] ap_phi_mux_x_0_phi_fu_90_p4;
wire    ap_block_pp0_stage0;
reg   [4:0] ap_phi_mux_y_0_phi_fu_101_p4;
wire   [63:0] zext_ln32_9_fu_188_p1;
wire   [63:0] zext_ln32_12_fu_235_p1;
wire   [0:0] icmp_ln29_fu_126_p2;
wire   [4:0] x_fu_108_p2;
wire   [4:0] add_ln32_fu_152_p2;
wire   [4:0] select_ln32_4_fu_158_p3;
wire   [4:0] select_ln32_fu_132_p3;
wire   [8:0] tmp_4_fu_170_p3;
wire   [9:0] zext_ln32_8_fu_178_p1;
wire   [9:0] zext_ln32_fu_148_p1;
wire   [9:0] add_ln32_5_fu_182_p2;
wire   [8:0] tmp_5_fu_199_p3;
wire   [5:0] tmp_6_fu_211_p3;
wire   [9:0] zext_ln32_11_fu_219_p1;
wire   [9:0] zext_ln32_10_fu_207_p1;
wire   [9:0] add_ln32_7_fu_223_p2;
wire   [9:0] zext_ln32_7_fu_166_p1;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_75 <= add_ln28_fu_120_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_75 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_0_reg_86 <= select_ln32_3_reg_248;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x_0_reg_86 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_0_reg_97 <= y_reg_258;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_0_reg_97 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_fu_114_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln32_8_reg_263 <= add_ln32_8_fu_229_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln28_reg_239 <= icmp_ln28_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln32_3_reg_248 <= select_ln32_3_fu_140_p3;
        y_reg_258 <= y_fu_193_p2;
    end
end

always @ (*) begin
    if ((icmp_ln28_fu_114_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln28_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_x_0_phi_fu_90_p4 = select_ln32_3_reg_248;
    end else begin
        ap_phi_mux_x_0_phi_fu_90_p4 = x_0_reg_86;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln28_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_y_0_phi_fu_101_p4 = y_reg_258;
    end else begin
        ap_phi_mux_y_0_phi_fu_101_p4 = y_0_reg_97;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln28_reg_239 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln28_fu_114_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln28_fu_114_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln28_fu_120_p2 = (indvar_flatten_reg_75 + 9'd1);

assign add_ln32_5_fu_182_p2 = (zext_ln32_8_fu_178_p1 + zext_ln32_fu_148_p1);

assign add_ln32_7_fu_223_p2 = (zext_ln32_11_fu_219_p1 + zext_ln32_10_fu_207_p1);

assign add_ln32_8_fu_229_p2 = (add_ln32_7_fu_223_p2 + zext_ln32_7_fu_166_p1);

assign add_ln32_fu_152_p2 = (ap_phi_mux_x_0_phi_fu_90_p4 + 5'd2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign icmp_ln28_fu_114_p2 = ((indvar_flatten_reg_75 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_126_p2 = ((ap_phi_mux_y_0_phi_fu_101_p4 == 5'd16) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln32_9_fu_188_p1;

assign output_r_address0 = zext_ln32_12_fu_235_p1;

assign output_r_d0 = input_r_q0;

assign select_ln32_3_fu_140_p3 = ((icmp_ln29_fu_126_p2[0:0] === 1'b1) ? x_fu_108_p2 : ap_phi_mux_x_0_phi_fu_90_p4);

assign select_ln32_4_fu_158_p3 = ((icmp_ln29_fu_126_p2[0:0] === 1'b1) ? add_ln32_fu_152_p2 : x_fu_108_p2);

assign select_ln32_fu_132_p3 = ((icmp_ln29_fu_126_p2[0:0] === 1'b1) ? 5'd0 : ap_phi_mux_y_0_phi_fu_101_p4);

assign tmp_4_fu_170_p3 = {{select_ln32_fu_132_p3}, {4'd0}};

assign tmp_5_fu_199_p3 = {{y_fu_193_p2}, {4'd0}};

assign tmp_6_fu_211_p3 = {{y_fu_193_p2}, {1'd0}};

assign x_fu_108_p2 = (ap_phi_mux_x_0_phi_fu_90_p4 + 5'd1);

assign y_fu_193_p2 = (select_ln32_fu_132_p3 + 5'd1);

assign zext_ln32_10_fu_207_p1 = tmp_5_fu_199_p3;

assign zext_ln32_11_fu_219_p1 = tmp_6_fu_211_p3;

assign zext_ln32_12_fu_235_p1 = add_ln32_8_reg_263;

assign zext_ln32_7_fu_166_p1 = select_ln32_4_fu_158_p3;

assign zext_ln32_8_fu_178_p1 = tmp_4_fu_170_p3;

assign zext_ln32_9_fu_188_p1 = add_ln32_5_fu_182_p2;

assign zext_ln32_fu_148_p1 = select_ln32_3_fu_140_p3;

endmodule //pad_1_16_9
